#![doc = include_str!("../readme.md")]
#![allow(non_camel_case_types)]

#[cfg(all(not(feature = "ilp64"), not(feature = "lp64_as_int")))]
pub type blas_int = i32;
#[cfg(all(not(feature = "ilp64"), feature = "lp64_as_int"))]
pub type blas_int = core::ffi::c_int;
#[cfg(feature = "ilp64")]
pub type blas_int = i64;

#[cfg(all(not(feature = "ilp64"), not(feature = "lp64_as_int")))]
pub type lapack_int = i32;
#[cfg(all(not(feature = "ilp64"), feature = "lp64_as_int"))]
pub type lapack_int = core::ffi::c_int;
#[cfg(feature = "ilp64")]
pub type lapack_int = i64;

/* automatically generated by rust-bindgen 0.71.1 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CBLAS_LAYOUT {
    CblasRowMajor = 101,
    CblasColMajor = 102,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CBLAS_TRANSPOSE {
    CblasNoTrans = 111,
    CblasTrans = 112,
    CblasConjTrans = 113,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CBLAS_UPLO {
    CblasUpper = 121,
    CblasLower = 122,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CBLAS_DIAG {
    CblasNonUnit = 131,
    CblasUnit = 132,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CBLAS_SIDE {
    CblasLeft = 141,
    CblasRight = 142,
}
pub use CBLAS_LAYOUT as CBLAS_ORDER;
