//! Base of current FFI.
//!
//! Declaration of types, enums, cargo feature controls, etc.
//!
//! This file is generated automatically.

pub(crate) use crate::kml_types::*;

/* automatically generated by rust-bindgen 0.71.1 */

pub const BLAS_SEQUENTIAL: u32 = 0;
pub const BLAS_THREAD: u32 = 1;
pub const BLAS_OPENMP: u32 = 2;
pub const VERSION_STRUCT_LEN: u32 = 100;
pub type BLASINT8 = i8;
pub type BLASUINT8 = u8;
pub type BLASLONG = c_long;
pub type BLASULONG = c_ulong;

pub type blas_complex_float = Complex<f32>;
pub type blas_complex_double = Complex<f64>;

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CBLAS_OFFSET {
    CblasRowOffset = 171,
    CblasColOffset = 172,
    CblasFixOffset = 173,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KBLASVersion {
    pub productName: [c_char; 100usize],
    pub productVersion: [c_char; 100usize],
    pub componentName: [c_char; 100usize],
    pub componentVersion: [c_char; 100usize],
    pub componentAppendInfo: [c_char; 100usize],
    pub softwareName: [c_char; 100usize],
    pub softwareVersion: [c_char; 100usize],
}
