//! Base of current FFI.
//!
//! Declaration of types, enums, cargo feature controls, etc.
//!
//! This file is generated automatically.

/* automatically generated by rust-bindgen 0.71.1 */

pub const KML_DEFAULT_ALLOCATE_ALIGN: u32 = 128;
pub const L1_CACHELINE_SIZE: u32 = 64;
pub const L2_CACHELINE_SIZE: u32 = 64;
pub const L3_CACHELINE_SIZE: u32 = 128;
pub const KML_VERSION_PART_LEN: u32 = 100;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KMLVersion {
    pub componentName: [::core::ffi::c_char; 100usize],
    pub componentVersion: [::core::ffi::c_char; 100usize],
    pub softwareName: [::core::ffi::c_char; 100usize],
    pub softwareVersion: [::core::ffi::c_char; 100usize],
    pub productName: [::core::ffi::c_char; 100usize],
    pub productVersion: [::core::ffi::c_char; 100usize],
    pub componentAppendInfo: [::core::ffi::c_char; 100usize],
}
pub type KSERVICEVersion = KMLVersion;
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlSetting {
    KML_VERBOSE = 0,
    KML_NUM_THREADS = 1,
    KML_THREAD_USING_POLICY = 2,
    KML_CFMA_ACCELERATION = 3,
    KML_CFMA_DRIVER_LOADED = 4,
    KML_SKIP_ZEROS = 5,
    KML_GEMM_TO_GEMM3M = 6,
    KML_BITWISE_COMPATIBILITY = 7,
    KML_FAST_IGNORE_DENORMS = 8,
    KML_ALLOCATE_POLICY = 9,
    KML_ALLOCATE_HUGEPAGE_SIZE = 10,
    KML_PXGETRF_FORCE_CALU = 11,
    KML_FAST_EIGENSOLVER = 12,
    KML_TSQR_CHECK = 13,
    KML_MPI_USE_SHARED_MEMORY = 14,
    SETTINGS_FLAG_COUNT = 15,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum SettingsStates {
    SETTINGS_ENTRY_NOT_INITED = 0,
    SETTINGS_ENTRY_INITED = 1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union KmlSettingValue {
    pub sizetValue: usize,
    pub intValue: ::core::ffi::c_int,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct KmlSettingEntry {
    pub value: KmlSettingValue,
    pub entryState: SettingsStates,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlCfmaAccelerationOption {
    KML_CFMA_DISABLED = 0,
    KML_CFMA_ENABLED = 1,
    KML_CFMA_FORCE_ENABLED = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlPxgetrfPivotingOption {
    KML_PXGETRF_FULLPIVOTING = 0,
    KML_PXGETRF_LOCALPIVOTING = 1,
    KML_PXGETRF_BLOCKPIVOTING = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlEigensolverOption {
    KML_EIGENSOLVER_EXACT = 0,
    KML_EIGENSOLVER_FAST = 1,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlTsqrCheckOption {
    KML_TSQR_CHECK_DEFAULT = 0,
    KML_TSQR_CHECK_WEAK = 1,
    KML_TSQR_CHECK_OFF = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlThreadUsingPolicyOption {
    KML_USE_ALL_THREADS = 0,
    KML_THRESHOLD_ENABLED = 1,
    KML_CROSSPOINTS_ENABLED = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlSkipZerosOption {
    KML_BLAS_NO_ZERO_SKIP = 0,
    KML_BLAS_NO_INTRUSIVE_ZERO_SKIP = 1,
    KML_BLAS_ENFORCED_ZERO_SKIP = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlGemmToGemM3MOption {
    KML_GEMM_TO_GEMM_3M_NEVER = 0,
    KML_GEMM_TO_GEMM_3M_OPTIMIZED = 1,
    KML_GEMM_TO_GEMM_3M_ALWAYS = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlMpiUseSharedMemoryOption {
    KML_MPI_SHARED_MEMORY_DISABLED = 0,
    KML_MPI_SHARED_MEMORY_ENABLED = 1,
    KML_MPI_SHARED_MEMORY_FORCE_ENABLED = 2,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlAllocatePolicy {
    KML_HUGEPAGES_NEVER = 0,
    KML_HUGEPAGES_ALWAYS = 1,
    KML_HUGEPAGES_AS_HEAP = 2,
    KML_COVERAGE_ALLOCATOR = 4,
}
#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum KmlErrorT {
    KML_INTERNAL_ERROR = -413,
    KML_WORK_MEM_ERROR = -1313,
    KML_NULL_PTR_ERROR = 100000,
}
