//! Library struct definition for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;

pub struct DyLoadLib {
    pub __libraries: Vec<libloading::Library>,
    pub __libraries_path: Vec<String>,
    pub openblas_set_num_threads: Option<unsafe extern "C" fn(num_threads: c_int)>,
    pub goto_set_num_threads: Option<unsafe extern "C" fn(num_threads: c_int)>,
    pub openblas_set_num_threads_local: Option<unsafe extern "C" fn(num_threads: c_int) -> c_int>,
    pub openblas_get_num_threads: Option<unsafe extern "C" fn() -> c_int>,
    pub openblas_get_num_procs: Option<unsafe extern "C" fn() -> c_int>,
    pub openblas_get_config: Option<unsafe extern "C" fn() -> *mut c_char>,
    pub openblas_get_corename: Option<unsafe extern "C" fn() -> *mut c_char>,
    pub openblas_set_threads_callback_function:
        Option<unsafe extern "C" fn(callback: openblas_threads_callback)>,
    pub openblas_get_parallel: Option<unsafe extern "C" fn() -> c_int>,
    pub cblas_sdsdot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: f32,
            x: *const f32,
            incx: blas_int,
            y: *const f32,
            incy: blas_int,
        ) -> f32,
    >,
    pub cblas_dsdot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const f32,
            incx: blas_int,
            y: *const f32,
            incy: blas_int,
        ) -> f64,
    >,
    pub cblas_sdot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const f32,
            incx: blas_int,
            y: *const f32,
            incy: blas_int,
        ) -> f32,
    >,
    pub cblas_ddot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const f64,
            incx: blas_int,
            y: *const f64,
            incy: blas_int,
        ) -> f64,
    >,
    pub cblas_cdotu: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
        ) -> openblas_complex_float,
    >,
    pub cblas_cdotc: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
        ) -> openblas_complex_float,
    >,
    pub cblas_zdotu: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
        ) -> openblas_complex_double,
    >,
    pub cblas_zdotc: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
        ) -> openblas_complex_double,
    >,
    pub cblas_cdotu_sub: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
            ret: *mut c_void,
        ),
    >,
    pub cblas_cdotc_sub: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
            ret: *mut c_void,
        ),
    >,
    pub cblas_zdotu_sub: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
            ret: *mut c_void,
        ),
    >,
    pub cblas_zdotc_sub: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *const c_void,
            incy: blas_int,
            ret: *mut c_void,
        ),
    >,
    pub cblas_sasum:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> f32>,
    pub cblas_dasum:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> f64>,
    pub cblas_scasum:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f32>,
    pub cblas_dzasum:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f64>,
    pub cblas_ssum: Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> f32>,
    pub cblas_dsum: Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> f64>,
    pub cblas_scsum:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f32>,
    pub cblas_dzsum:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f64>,
    pub cblas_snrm2:
        Option<unsafe extern "C" fn(N: blas_int, X: *const f32, incX: blas_int) -> f32>,
    pub cblas_dnrm2:
        Option<unsafe extern "C" fn(N: blas_int, X: *const f64, incX: blas_int) -> f64>,
    pub cblas_scnrm2:
        Option<unsafe extern "C" fn(N: blas_int, X: *const c_void, incX: blas_int) -> f32>,
    pub cblas_dznrm2:
        Option<unsafe extern "C" fn(N: blas_int, X: *const c_void, incX: blas_int) -> f64>,
    pub cblas_isamax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> usize>,
    pub cblas_idamax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> usize>,
    pub cblas_icamax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_izamax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_isamin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> usize>,
    pub cblas_idamin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> usize>,
    pub cblas_icamin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_izamin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_samax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> f32>,
    pub cblas_damax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> f64>,
    pub cblas_scamax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f32>,
    pub cblas_dzamax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f64>,
    pub cblas_samin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> f32>,
    pub cblas_damin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> f64>,
    pub cblas_scamin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f32>,
    pub cblas_dzamin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> f64>,
    pub cblas_ismax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> usize>,
    pub cblas_idmax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> usize>,
    pub cblas_icmax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_izmax:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_ismin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f32, incx: blas_int) -> usize>,
    pub cblas_idmin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const f64, incx: blas_int) -> usize>,
    pub cblas_icmin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_izmin:
        Option<unsafe extern "C" fn(n: blas_int, x: *const c_void, incx: blas_int) -> usize>,
    pub cblas_saxpy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: f32,
            x: *const f32,
            incx: blas_int,
            y: *mut f32,
            incy: blas_int,
        ),
    >,
    pub cblas_daxpy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: f64,
            x: *const f64,
            incx: blas_int,
            y: *mut f64,
            incy: blas_int,
        ),
    >,
    pub cblas_caxpy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: *const c_void,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_zaxpy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: *const c_void,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_caxpyc: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: *const c_void,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_zaxpyc: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: *const c_void,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_scopy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const f32,
            incx: blas_int,
            y: *mut f32,
            incy: blas_int,
        ),
    >,
    pub cblas_dcopy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const f64,
            incx: blas_int,
            y: *mut f64,
            incy: blas_int,
        ),
    >,
    pub cblas_ccopy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_zcopy: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_sswap: Option<
        unsafe extern "C" fn(n: blas_int, x: *mut f32, incx: blas_int, y: *mut f32, incy: blas_int),
    >,
    pub cblas_dswap: Option<
        unsafe extern "C" fn(n: blas_int, x: *mut f64, incx: blas_int, y: *mut f64, incy: blas_int),
    >,
    pub cblas_cswap: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *mut c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_zswap: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *mut c_void,
            incx: blas_int,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_srot: Option<
        unsafe extern "C" fn(
            N: blas_int,
            X: *mut f32,
            incX: blas_int,
            Y: *mut f32,
            incY: blas_int,
            c: f32,
            s: f32,
        ),
    >,
    pub cblas_drot: Option<
        unsafe extern "C" fn(
            N: blas_int,
            X: *mut f64,
            incX: blas_int,
            Y: *mut f64,
            incY: blas_int,
            c: f64,
            s: f64,
        ),
    >,
    pub cblas_csrot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incY: blas_int,
            c: f32,
            s: f32,
        ),
    >,
    pub cblas_zdrot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const c_void,
            incx: blas_int,
            y: *mut c_void,
            incY: blas_int,
            c: f64,
            s: f64,
        ),
    >,
    pub cblas_srotg:
        Option<unsafe extern "C" fn(a: *mut f32, b: *mut f32, c: *mut f32, s: *mut f32)>,
    pub cblas_drotg:
        Option<unsafe extern "C" fn(a: *mut f64, b: *mut f64, c: *mut f64, s: *mut f64)>,
    pub cblas_crotg:
        Option<unsafe extern "C" fn(a: *mut c_void, b: *mut c_void, c: *mut f32, s: *mut c_void)>,
    pub cblas_zrotg:
        Option<unsafe extern "C" fn(a: *mut c_void, b: *mut c_void, c: *mut f64, s: *mut c_void)>,
    pub cblas_srotm: Option<
        unsafe extern "C" fn(
            N: blas_int,
            X: *mut f32,
            incX: blas_int,
            Y: *mut f32,
            incY: blas_int,
            P: *const f32,
        ),
    >,
    pub cblas_drotm: Option<
        unsafe extern "C" fn(
            N: blas_int,
            X: *mut f64,
            incX: blas_int,
            Y: *mut f64,
            incY: blas_int,
            P: *const f64,
        ),
    >,
    pub cblas_srotmg: Option<
        unsafe extern "C" fn(d1: *mut f32, d2: *mut f32, b1: *mut f32, b2: f32, P: *mut f32),
    >,
    pub cblas_drotmg: Option<
        unsafe extern "C" fn(d1: *mut f64, d2: *mut f64, b1: *mut f64, b2: f64, P: *mut f64),
    >,
    pub cblas_sscal:
        Option<unsafe extern "C" fn(N: blas_int, alpha: f32, X: *mut f32, incX: blas_int)>,
    pub cblas_dscal:
        Option<unsafe extern "C" fn(N: blas_int, alpha: f64, X: *mut f64, incX: blas_int)>,
    pub cblas_cscal: Option<
        unsafe extern "C" fn(N: blas_int, alpha: *const c_void, X: *mut c_void, incX: blas_int),
    >,
    pub cblas_zscal: Option<
        unsafe extern "C" fn(N: blas_int, alpha: *const c_void, X: *mut c_void, incX: blas_int),
    >,
    pub cblas_csscal:
        Option<unsafe extern "C" fn(N: blas_int, alpha: f32, X: *mut c_void, incX: blas_int)>,
    pub cblas_zdscal:
        Option<unsafe extern "C" fn(N: blas_int, alpha: f64, X: *mut c_void, incX: blas_int)>,
    pub cblas_sgemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            trans: CBLAS_TRANSPOSE,
            m: blas_int,
            n: blas_int,
            alpha: f32,
            a: *const f32,
            lda: blas_int,
            x: *const f32,
            incx: blas_int,
            beta: f32,
            y: *mut f32,
            incy: blas_int,
        ),
    >,
    pub cblas_dgemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            trans: CBLAS_TRANSPOSE,
            m: blas_int,
            n: blas_int,
            alpha: f64,
            a: *const f64,
            lda: blas_int,
            x: *const f64,
            incx: blas_int,
            beta: f64,
            y: *mut f64,
            incy: blas_int,
        ),
    >,
    pub cblas_cgemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            trans: CBLAS_TRANSPOSE,
            m: blas_int,
            n: blas_int,
            alpha: *const c_void,
            a: *const c_void,
            lda: blas_int,
            x: *const c_void,
            incx: blas_int,
            beta: *const c_void,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_zgemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            trans: CBLAS_TRANSPOSE,
            m: blas_int,
            n: blas_int,
            alpha: *const c_void,
            a: *const c_void,
            lda: blas_int,
            x: *const c_void,
            incx: blas_int,
            beta: *const c_void,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_sger: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            M: blas_int,
            N: blas_int,
            alpha: f32,
            X: *const f32,
            incX: blas_int,
            Y: *const f32,
            incY: blas_int,
            A: *mut f32,
            lda: blas_int,
        ),
    >,
    pub cblas_dger: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            M: blas_int,
            N: blas_int,
            alpha: f64,
            X: *const f64,
            incX: blas_int,
            Y: *const f64,
            incY: blas_int,
            A: *mut f64,
            lda: blas_int,
        ),
    >,
    pub cblas_cgeru: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_cgerc: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_zgeru: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_zgerc: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_strsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const f32,
            lda: blas_int,
            X: *mut f32,
            incX: blas_int,
        ),
    >,
    pub cblas_dtrsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const f64,
            lda: blas_int,
            X: *mut f64,
            incX: blas_int,
        ),
    >,
    pub cblas_ctrsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ztrsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_strmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const f32,
            lda: blas_int,
            X: *mut f32,
            incX: blas_int,
        ),
    >,
    pub cblas_dtrmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const f64,
            lda: blas_int,
            X: *mut f64,
            incX: blas_int,
        ),
    >,
    pub cblas_ctrmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ztrmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ssyr: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            X: *const f32,
            incX: blas_int,
            A: *mut f32,
            lda: blas_int,
        ),
    >,
    pub cblas_dsyr: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            X: *const f64,
            incX: blas_int,
            A: *mut f64,
            lda: blas_int,
        ),
    >,
    pub cblas_cher: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            X: *const c_void,
            incX: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_zher: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            X: *const c_void,
            incX: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_ssyr2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            X: *const f32,
            incX: blas_int,
            Y: *const f32,
            incY: blas_int,
            A: *mut f32,
            lda: blas_int,
        ),
    >,
    pub cblas_dsyr2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            X: *const f64,
            incX: blas_int,
            Y: *const f64,
            incY: blas_int,
            A: *mut f64,
            lda: blas_int,
        ),
    >,
    pub cblas_cher2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_zher2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            A: *mut c_void,
            lda: blas_int,
        ),
    >,
    pub cblas_sgbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            KL: blas_int,
            KU: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            X: *const f32,
            incX: blas_int,
            beta: f32,
            Y: *mut f32,
            incY: blas_int,
        ),
    >,
    pub cblas_dgbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            KL: blas_int,
            KU: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            X: *const f64,
            incX: blas_int,
            beta: f64,
            Y: *mut f64,
            incY: blas_int,
        ),
    >,
    pub cblas_cgbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            KL: blas_int,
            KU: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_zgbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            KL: blas_int,
            KU: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_ssbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            X: *const f32,
            incX: blas_int,
            beta: f32,
            Y: *mut f32,
            incY: blas_int,
        ),
    >,
    pub cblas_dsbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            K: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            X: *const f64,
            incX: blas_int,
            beta: f64,
            Y: *mut f64,
            incY: blas_int,
        ),
    >,
    pub cblas_stbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const f32,
            lda: blas_int,
            X: *mut f32,
            incX: blas_int,
        ),
    >,
    pub cblas_dtbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const f64,
            lda: blas_int,
            X: *mut f64,
            incX: blas_int,
        ),
    >,
    pub cblas_ctbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ztbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_stbsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const f32,
            lda: blas_int,
            X: *mut f32,
            incX: blas_int,
        ),
    >,
    pub cblas_dtbsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const f64,
            lda: blas_int,
            X: *mut f64,
            incX: blas_int,
        ),
    >,
    pub cblas_ctbsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ztbsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            K: blas_int,
            A: *const c_void,
            lda: blas_int,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_stpmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const f32,
            X: *mut f32,
            incX: blas_int,
        ),
    >,
    pub cblas_dtpmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const f64,
            X: *mut f64,
            incX: blas_int,
        ),
    >,
    pub cblas_ctpmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const c_void,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ztpmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const c_void,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_stpsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const f32,
            X: *mut f32,
            incX: blas_int,
        ),
    >,
    pub cblas_dtpsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const f64,
            X: *mut f64,
            incX: blas_int,
        ),
    >,
    pub cblas_ctpsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const c_void,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ztpsv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            N: blas_int,
            Ap: *const c_void,
            X: *mut c_void,
            incX: blas_int,
        ),
    >,
    pub cblas_ssymv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            X: *const f32,
            incX: blas_int,
            beta: f32,
            Y: *mut f32,
            incY: blas_int,
        ),
    >,
    pub cblas_dsymv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            X: *const f64,
            incX: blas_int,
            beta: f64,
            Y: *mut f64,
            incY: blas_int,
        ),
    >,
    pub cblas_chemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_zhemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_sspmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            Ap: *const f32,
            X: *const f32,
            incX: blas_int,
            beta: f32,
            Y: *mut f32,
            incY: blas_int,
        ),
    >,
    pub cblas_dspmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            Ap: *const f64,
            X: *const f64,
            incX: blas_int,
            beta: f64,
            Y: *mut f64,
            incY: blas_int,
        ),
    >,
    pub cblas_sspr: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            X: *const f32,
            incX: blas_int,
            Ap: *mut f32,
        ),
    >,
    pub cblas_dspr: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            X: *const f64,
            incX: blas_int,
            Ap: *mut f64,
        ),
    >,
    pub cblas_chpr: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            X: *const c_void,
            incX: blas_int,
            A: *mut c_void,
        ),
    >,
    pub cblas_zhpr: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            X: *const c_void,
            incX: blas_int,
            A: *mut c_void,
        ),
    >,
    pub cblas_sspr2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f32,
            X: *const f32,
            incX: blas_int,
            Y: *const f32,
            incY: blas_int,
            A: *mut f32,
        ),
    >,
    pub cblas_dspr2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: f64,
            X: *const f64,
            incX: blas_int,
            Y: *const f64,
            incY: blas_int,
            A: *mut f64,
        ),
    >,
    pub cblas_chpr2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            Ap: *mut c_void,
        ),
    >,
    pub cblas_zhpr2: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            X: *const c_void,
            incX: blas_int,
            Y: *const c_void,
            incY: blas_int,
            Ap: *mut c_void,
        ),
    >,
    pub cblas_chbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_zhbmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_chpmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            Ap: *const c_void,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_zhpmv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            N: blas_int,
            alpha: *const c_void,
            Ap: *const c_void,
            X: *const c_void,
            incX: blas_int,
            beta: *const c_void,
            Y: *mut c_void,
            incY: blas_int,
        ),
    >,
    pub cblas_sgemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            B: *const f32,
            ldb: blas_int,
            beta: f32,
            C: *mut f32,
            ldc: blas_int,
        ),
    >,
    pub cblas_dgemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            B: *const f64,
            ldb: blas_int,
            beta: f64,
            C: *mut f64,
            ldc: blas_int,
        ),
    >,
    pub cblas_cgemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_cgemm3m: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zgemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zgemm3m: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_sgemmt: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            B: *const f32,
            ldb: blas_int,
            beta: f32,
            C: *mut f32,
            ldc: blas_int,
        ),
    >,
    pub cblas_dgemmt: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            K: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            B: *const f64,
            ldb: blas_int,
            beta: f64,
            C: *mut f64,
            ldc: blas_int,
        ),
    >,
    pub cblas_cgemmt: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zgemmt: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_ssymm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            M: blas_int,
            N: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            B: *const f32,
            ldb: blas_int,
            beta: f32,
            C: *mut f32,
            ldc: blas_int,
        ),
    >,
    pub cblas_dsymm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            M: blas_int,
            N: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            B: *const f64,
            ldb: blas_int,
            beta: f64,
            C: *mut f64,
            ldc: blas_int,
        ),
    >,
    pub cblas_csymm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zsymm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_ssyrk: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            beta: f32,
            C: *mut f32,
            ldc: blas_int,
        ),
    >,
    pub cblas_dsyrk: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            beta: f64,
            C: *mut f64,
            ldc: blas_int,
        ),
    >,
    pub cblas_csyrk: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zsyrk: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_ssyr2k: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            B: *const f32,
            ldb: blas_int,
            beta: f32,
            C: *mut f32,
            ldc: blas_int,
        ),
    >,
    pub cblas_dsyr2k: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            B: *const f64,
            ldb: blas_int,
            beta: f64,
            C: *mut f64,
            ldc: blas_int,
        ),
    >,
    pub cblas_csyr2k: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zsyr2k: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_strmm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            B: *mut f32,
            ldb: blas_int,
        ),
    >,
    pub cblas_dtrmm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            B: *mut f64,
            ldb: blas_int,
        ),
    >,
    pub cblas_ctrmm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *mut c_void,
            ldb: blas_int,
        ),
    >,
    pub cblas_ztrmm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *mut c_void,
            ldb: blas_int,
        ),
    >,
    pub cblas_strsm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: f32,
            A: *const f32,
            lda: blas_int,
            B: *mut f32,
            ldb: blas_int,
        ),
    >,
    pub cblas_dtrsm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: f64,
            A: *const f64,
            lda: blas_int,
            B: *mut f64,
            ldb: blas_int,
        ),
    >,
    pub cblas_ctrsm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *mut c_void,
            ldb: blas_int,
        ),
    >,
    pub cblas_ztrsm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            TransA: CBLAS_TRANSPOSE,
            Diag: CBLAS_DIAG,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *mut c_void,
            ldb: blas_int,
        ),
    >,
    pub cblas_chemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zhemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Side: CBLAS_SIDE,
            Uplo: CBLAS_UPLO,
            M: blas_int,
            N: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: *const c_void,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_cherk: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const c_void,
            lda: blas_int,
            beta: f32,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zherk: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: f64,
            A: *const c_void,
            lda: blas_int,
            beta: f64,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_cher2k: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: f32,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_zher2k: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            Uplo: CBLAS_UPLO,
            Trans: CBLAS_TRANSPOSE,
            N: blas_int,
            K: blas_int,
            alpha: *const c_void,
            A: *const c_void,
            lda: blas_int,
            B: *const c_void,
            ldb: blas_int,
            beta: f64,
            C: *mut c_void,
            ldc: blas_int,
        ),
    >,
    pub cblas_xerbla:
        Option<unsafe extern "C" fn(p: blas_int, rout: *const c_char, form: *const c_char)>,
    pub cblas_saxpby: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: f32,
            x: *const f32,
            incx: blas_int,
            beta: f32,
            y: *mut f32,
            incy: blas_int,
        ),
    >,
    pub cblas_daxpby: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: f64,
            x: *const f64,
            incx: blas_int,
            beta: f64,
            y: *mut f64,
            incy: blas_int,
        ),
    >,
    pub cblas_caxpby: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: *const c_void,
            x: *const c_void,
            incx: blas_int,
            beta: *const c_void,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_zaxpby: Option<
        unsafe extern "C" fn(
            n: blas_int,
            alpha: *const c_void,
            x: *const c_void,
            incx: blas_int,
            beta: *const c_void,
            y: *mut c_void,
            incy: blas_int,
        ),
    >,
    pub cblas_somatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: f32,
            a: *const f32,
            clda: blas_int,
            b: *mut f32,
            cldb: blas_int,
        ),
    >,
    pub cblas_domatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: f64,
            a: *const f64,
            clda: blas_int,
            b: *mut f64,
            cldb: blas_int,
        ),
    >,
    pub cblas_comatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: *const f32,
            a: *const f32,
            clda: blas_int,
            b: *mut f32,
            cldb: blas_int,
        ),
    >,
    pub cblas_zomatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: *const f64,
            a: *const f64,
            clda: blas_int,
            b: *mut f64,
            cldb: blas_int,
        ),
    >,
    pub cblas_simatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: f32,
            a: *mut f32,
            clda: blas_int,
            cldb: blas_int,
        ),
    >,
    pub cblas_dimatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: f64,
            a: *mut f64,
            clda: blas_int,
            cldb: blas_int,
        ),
    >,
    pub cblas_cimatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: *const f32,
            a: *mut f32,
            clda: blas_int,
            cldb: blas_int,
        ),
    >,
    pub cblas_zimatcopy: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            CTRANS: CBLAS_TRANSPOSE,
            crows: blas_int,
            ccols: blas_int,
            calpha: *const f64,
            a: *mut f64,
            clda: blas_int,
            cldb: blas_int,
        ),
    >,
    pub cblas_sgeadd: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            crows: blas_int,
            ccols: blas_int,
            calpha: f32,
            a: *const f32,
            clda: blas_int,
            cbeta: f32,
            c: *mut f32,
            cldc: blas_int,
        ),
    >,
    pub cblas_dgeadd: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            crows: blas_int,
            ccols: blas_int,
            calpha: f64,
            a: *const f64,
            clda: blas_int,
            cbeta: f64,
            c: *mut f64,
            cldc: blas_int,
        ),
    >,
    pub cblas_cgeadd: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            crows: blas_int,
            ccols: blas_int,
            calpha: *const f32,
            a: *const f32,
            clda: blas_int,
            cbeta: *const f32,
            c: *mut f32,
            cldc: blas_int,
        ),
    >,
    pub cblas_zgeadd: Option<
        unsafe extern "C" fn(
            CORDER: CBLAS_ORDER,
            crows: blas_int,
            ccols: blas_int,
            calpha: *const f64,
            a: *const f64,
            clda: blas_int,
            cbeta: *const f64,
            c: *mut f64,
            cldc: blas_int,
        ),
    >,
    pub cblas_sgemm_batch: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA_array: *const CBLAS_TRANSPOSE,
            TransB_array: *const CBLAS_TRANSPOSE,
            M_array: *const blas_int,
            N_array: *const blas_int,
            K_array: *const blas_int,
            alpha_array: *const f32,
            A_array: *mut *const f32,
            lda_array: *const blas_int,
            B_array: *mut *const f32,
            ldb_array: *const blas_int,
            beta_array: *const f32,
            C_array: *mut *mut f32,
            ldc_array: *const blas_int,
            group_count: blas_int,
            group_size: *const blas_int,
        ),
    >,
    pub cblas_dgemm_batch: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA_array: *const CBLAS_TRANSPOSE,
            TransB_array: *const CBLAS_TRANSPOSE,
            M_array: *const blas_int,
            N_array: *const blas_int,
            K_array: *const blas_int,
            alpha_array: *const f64,
            A_array: *mut *const f64,
            lda_array: *const blas_int,
            B_array: *mut *const f64,
            ldb_array: *const blas_int,
            beta_array: *const f64,
            C_array: *mut *mut f64,
            ldc_array: *const blas_int,
            group_count: blas_int,
            group_size: *const blas_int,
        ),
    >,
    pub cblas_cgemm_batch: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA_array: *const CBLAS_TRANSPOSE,
            TransB_array: *const CBLAS_TRANSPOSE,
            M_array: *const blas_int,
            N_array: *const blas_int,
            K_array: *const blas_int,
            alpha_array: *const c_void,
            A_array: *mut *const c_void,
            lda_array: *const blas_int,
            B_array: *mut *const c_void,
            ldb_array: *const blas_int,
            beta_array: *const c_void,
            C_array: *mut *mut c_void,
            ldc_array: *const blas_int,
            group_count: blas_int,
            group_size: *const blas_int,
        ),
    >,
    pub cblas_zgemm_batch: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA_array: *const CBLAS_TRANSPOSE,
            TransB_array: *const CBLAS_TRANSPOSE,
            M_array: *const blas_int,
            N_array: *const blas_int,
            K_array: *const blas_int,
            alpha_array: *const c_void,
            A_array: *mut *const c_void,
            lda_array: *const blas_int,
            B_array: *mut *const c_void,
            ldb_array: *const blas_int,
            beta_array: *const c_void,
            C_array: *mut *mut c_void,
            ldc_array: *const blas_int,
            group_count: blas_int,
            group_size: *const blas_int,
        ),
    >,
    pub cblas_sbstobf16: Option<
        unsafe extern "C" fn(
            n: blas_int,
            in_: *const f32,
            incin: blas_int,
            out: *mut bfloat16,
            incout: blas_int,
        ),
    >,
    pub cblas_sbdtobf16: Option<
        unsafe extern "C" fn(
            n: blas_int,
            in_: *const f64,
            incin: blas_int,
            out: *mut bfloat16,
            incout: blas_int,
        ),
    >,
    pub cblas_sbf16tos: Option<
        unsafe extern "C" fn(
            n: blas_int,
            in_: *const bfloat16,
            incin: blas_int,
            out: *mut f32,
            incout: blas_int,
        ),
    >,
    pub cblas_dbf16tod: Option<
        unsafe extern "C" fn(
            n: blas_int,
            in_: *const bfloat16,
            incin: blas_int,
            out: *mut f64,
            incout: blas_int,
        ),
    >,
    pub cblas_sbdot: Option<
        unsafe extern "C" fn(
            n: blas_int,
            x: *const bfloat16,
            incx: blas_int,
            y: *const bfloat16,
            incy: blas_int,
        ) -> f32,
    >,
    pub cblas_sbgemv: Option<
        unsafe extern "C" fn(
            order: CBLAS_ORDER,
            trans: CBLAS_TRANSPOSE,
            m: blas_int,
            n: blas_int,
            alpha: f32,
            a: *const bfloat16,
            lda: blas_int,
            x: *const bfloat16,
            incx: blas_int,
            beta: f32,
            y: *mut f32,
            incy: blas_int,
        ),
    >,
    pub cblas_sbgemm: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA: CBLAS_TRANSPOSE,
            TransB: CBLAS_TRANSPOSE,
            M: blas_int,
            N: blas_int,
            K: blas_int,
            alpha: f32,
            A: *const bfloat16,
            lda: blas_int,
            B: *const bfloat16,
            ldb: blas_int,
            beta: f32,
            C: *mut f32,
            ldc: blas_int,
        ),
    >,
    pub cblas_sbgemm_batch: Option<
        unsafe extern "C" fn(
            Order: CBLAS_ORDER,
            TransA_array: *const CBLAS_TRANSPOSE,
            TransB_array: *const CBLAS_TRANSPOSE,
            M_array: *const blas_int,
            N_array: *const blas_int,
            K_array: *const blas_int,
            alpha_array: *const f32,
            A_array: *mut *const bfloat16,
            lda_array: *const blas_int,
            B_array: *mut *const bfloat16,
            ldb_array: *const blas_int,
            beta_array: *const f32,
            C_array: *mut *mut f32,
            ldc_array: *const blas_int,
            group_count: blas_int,
            group_size: *const blas_int,
        ),
    >,
    pub omp_set_num_threads: Option<unsafe extern "C" fn(arg1: c_int)>,
    pub omp_get_max_threads: Option<unsafe extern "C" fn() -> c_int>,
}
