[package]
name = "rstsr-openblas-ffi"
description = "OpenBLAS FFI bindings"
readme = "readme.md"

version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
rstsr-lapack-ffi = { workspace = true, features = ["cblas"] }
libloading = { workspace = true }

[features]
default = ["blas", "cblas", "lapack", "dynamic_loading"]

ilp64 = []
dynamic_loading = []

blas = []
cblas = []
lapack = []
lapacke = []

quad_precision = []
ex_precision = []
