[package]
name = "rstsr-openblas-ffi"
version = "0.3.1"
description = "OpenBLAS FFI bindings"
readme = "readme.md"

edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
libloading = { workspace = true }

[features]
default = []

ilp64 = []
dynamic_loading = []

quad_precision = []
ex_precision = []
