[package]
name = "rstsr-openblas-ffi"
version = "0.3.0"
description = "OpenBLAS FFI bindings"
readme = "readme.md"

edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]

[features]
default = []
ilp64 = []
quad_precision = []
ex_precision = []
