//! Library struct definition for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;

pub struct DyLoadLib {
    pub __libraries: Vec<libloading::Library>,
    pub xerbla_: Option<unsafe extern "C" fn(arg1: *mut c_char, arg2: *mut c_void)>,
    pub srot_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut f32,
            arg3: *const blas_int,
            arg4: *mut f32,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const f32,
        ),
    >,
    pub srotg_: Option<
        unsafe extern "C" fn(arg1: *mut f32, arg2: *mut f32, arg3: *mut f32, arg4: *mut f32),
    >,
    pub srotm_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut f32,
            arg3: *const blas_int,
            arg4: *mut f32,
            arg5: *const blas_int,
            arg6: *const f32,
        ),
    >,
    pub srotmg_: Option<
        unsafe extern "C" fn(
            arg1: *mut f32,
            arg2: *mut f32,
            arg3: *mut f32,
            arg4: *const f32,
            arg5: *mut f32,
        ),
    >,
    pub sswap_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut f32,
            arg3: *const blas_int,
            arg4: *mut f32,
            arg5: *const blas_int,
        ),
    >,
    pub scopy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const blas_int,
            arg4: *mut f32,
            arg5: *const blas_int,
        ),
    >,
    pub saxpy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const f32,
            arg4: *const blas_int,
            arg5: *mut f32,
            arg6: *const blas_int,
        ),
    >,
    pub sdotsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const blas_int,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *mut f32,
        ),
    >,
    pub sdsdotsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const f32,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const blas_int,
            arg7: *mut f32,
        ),
    >,
    pub sscal_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *mut f32,
            arg4: *const blas_int,
        ),
    >,
    pub snrm2sub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const blas_int,
            arg4: *mut f32,
        ),
    >,
    pub sasumsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const blas_int,
            arg4: *mut f32,
        ),
    >,
    pub isamaxsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const blas_int,
            arg4: *mut blas_int,
        ),
    >,
    pub drot_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut f64,
            arg3: *const blas_int,
            arg4: *mut f64,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const f64,
        ),
    >,
    pub drotg_: Option<
        unsafe extern "C" fn(arg1: *mut f64, arg2: *mut f64, arg3: *mut f64, arg4: *mut f64),
    >,
    pub drotm_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut f64,
            arg3: *const blas_int,
            arg4: *mut f64,
            arg5: *const blas_int,
            arg6: *const f64,
        ),
    >,
    pub drotmg_: Option<
        unsafe extern "C" fn(
            arg1: *mut f64,
            arg2: *mut f64,
            arg3: *mut f64,
            arg4: *const f64,
            arg5: *mut f64,
        ),
    >,
    pub dswap_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut f64,
            arg3: *const blas_int,
            arg4: *mut f64,
            arg5: *const blas_int,
        ),
    >,
    pub dcopy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *const blas_int,
            arg4: *mut f64,
            arg5: *const blas_int,
        ),
    >,
    pub daxpy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *const f64,
            arg4: *const blas_int,
            arg5: *mut f64,
            arg6: *const blas_int,
        ),
    >,
    pub dsdotsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *const blas_int,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *mut f64,
        ),
    >,
    pub ddotsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *const blas_int,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *mut f64,
        ),
    >,
    pub dscal_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *mut f64,
            arg4: *const blas_int,
        ),
    >,
    pub dnrm2sub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *const blas_int,
            arg4: *mut f64,
        ),
    >,
    pub dasumsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *const blas_int,
            arg4: *mut f64,
        ),
    >,
    pub idamaxsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *const blas_int,
            arg4: *mut blas_int,
        ),
    >,
    pub crotg_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_void,
            arg2: *mut c_void,
            arg3: *mut f32,
            arg4: *mut c_void,
        ),
    >,
    pub csrot_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            X: *mut c_void,
            arg2: *const blas_int,
            arg3: *mut c_void,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const f32,
        ),
    >,
    pub cswap_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut c_void,
            arg3: *const blas_int,
            arg4: *mut c_void,
            arg5: *const blas_int,
        ),
    >,
    pub ccopy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut c_void,
            arg5: *const blas_int,
        ),
    >,
    pub caxpy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const c_void,
            arg4: *const blas_int,
            arg5: *mut c_void,
            arg6: *const blas_int,
        ),
    >,
    pub cdotcsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
        ),
    >,
    pub cdotusub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
        ),
    >,
    pub cscal_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *mut c_void,
            arg4: *const blas_int,
        ),
    >,
    pub icamaxsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut blas_int,
        ),
    >,
    pub csscal_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f32,
            arg3: *mut c_void,
            arg4: *const blas_int,
        ),
    >,
    pub scnrm2sub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut f32,
        ),
    >,
    pub scasumsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut f32,
        ),
    >,
    pub scabs1sub_: Option<unsafe extern "C" fn(arg1: *const c_void, arg2: *mut f32)>,
    pub zrotg_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_void,
            arg2: *mut c_void,
            arg3: *mut f64,
            arg4: *mut c_void,
        ),
    >,
    pub zdrot_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            X: *mut c_void,
            arg2: *const blas_int,
            arg3: *mut c_void,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const f64,
        ),
    >,
    pub zswap_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *mut c_void,
            arg3: *const blas_int,
            arg4: *mut c_void,
            arg5: *const blas_int,
        ),
    >,
    pub zcopy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut c_void,
            arg5: *const blas_int,
        ),
    >,
    pub zaxpy_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const c_void,
            arg4: *const blas_int,
            arg5: *mut c_void,
            arg6: *const blas_int,
        ),
    >,
    pub zdotcsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
        ),
    >,
    pub zdotusub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
        ),
    >,
    pub zdscal_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const f64,
            arg3: *mut c_void,
            arg4: *const blas_int,
        ),
    >,
    pub zscal_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *mut c_void,
            arg4: *const blas_int,
        ),
    >,
    pub dznrm2sub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut f64,
        ),
    >,
    pub dzasumsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut f64,
        ),
    >,
    pub izamaxsub_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const c_void,
            arg3: *const blas_int,
            arg4: *mut blas_int,
        ),
    >,
    pub dcabs1sub_: Option<unsafe extern "C" fn(arg1: *const c_void, arg2: *mut f64)>,
    pub sgemv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const f32,
            arg5: *const f32,
            arg6: *const blas_int,
            arg7: *const f32,
            arg8: *const blas_int,
            arg9: *const f32,
            arg10: *mut f32,
            arg11: *const blas_int,
        ),
    >,
    pub sgbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const f32,
            arg8: *const blas_int,
            arg9: *const f32,
            arg10: *const blas_int,
            arg11: *const f32,
            arg12: *mut f32,
            arg13: *const blas_int,
        ),
    >,
    pub ssymv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *const f32,
            arg9: *mut f32,
            arg10: *const blas_int,
        ),
    >,
    pub ssbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const f32,
            arg5: *const f32,
            arg6: *const blas_int,
            arg7: *const f32,
            arg8: *const blas_int,
            arg9: *const f32,
            arg10: *mut f32,
            arg11: *const blas_int,
        ),
    >,
    pub sspmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const f32,
            arg6: *const blas_int,
            arg7: *const f32,
            arg8: *mut f32,
            arg9: *const blas_int,
        ),
    >,
    pub strmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const blas_int,
            arg7: *mut f32,
            arg8: *const blas_int,
        ),
    >,
    pub stbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *mut f32,
            arg9: *const blas_int,
        ),
    >,
    pub strsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const blas_int,
            arg7: *mut f32,
            arg8: *const blas_int,
        ),
    >,
    pub stbsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *mut f32,
            arg9: *const blas_int,
        ),
    >,
    pub stpmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *mut f32,
            arg7: *const blas_int,
        ),
    >,
    pub stpsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *mut f32,
            arg7: *const blas_int,
        ),
    >,
    pub sger_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *mut f32,
            arg9: *const blas_int,
        ),
    >,
    pub ssyr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *mut f32,
            arg7: *const blas_int,
        ),
    >,
    pub sspr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *mut f32,
        ),
    >,
    pub sspr2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *mut f32,
        ),
    >,
    pub ssyr2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const f32,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *mut f32,
            arg9: *const blas_int,
        ),
    >,
    pub dgemv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const f64,
            arg5: *const f64,
            arg6: *const blas_int,
            arg7: *const f64,
            arg8: *const blas_int,
            arg9: *const f64,
            arg10: *mut f64,
            arg11: *const blas_int,
        ),
    >,
    pub dgbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const f64,
            arg8: *const blas_int,
            arg9: *const f64,
            arg10: *const blas_int,
            arg11: *const f64,
            arg12: *mut f64,
            arg13: *const blas_int,
        ),
    >,
    pub dsymv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *const f64,
            arg9: *mut f64,
            arg10: *const blas_int,
        ),
    >,
    pub dsbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const f64,
            arg5: *const f64,
            arg6: *const blas_int,
            arg7: *const f64,
            arg8: *const blas_int,
            arg9: *const f64,
            arg10: *mut f64,
            arg11: *const blas_int,
        ),
    >,
    pub dspmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const f64,
            arg6: *const blas_int,
            arg7: *const f64,
            arg8: *mut f64,
            arg9: *const blas_int,
        ),
    >,
    pub dtrmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const blas_int,
            arg7: *mut f64,
            arg8: *const blas_int,
        ),
    >,
    pub dtbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *mut f64,
            arg9: *const blas_int,
        ),
    >,
    pub dtrsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const blas_int,
            arg7: *mut f64,
            arg8: *const blas_int,
        ),
    >,
    pub dtbsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *mut f64,
            arg9: *const blas_int,
        ),
    >,
    pub dtpmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *mut f64,
            arg7: *const blas_int,
        ),
    >,
    pub dtpsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *mut f64,
            arg7: *const blas_int,
        ),
    >,
    pub dger_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *mut f64,
            arg9: *const blas_int,
        ),
    >,
    pub dsyr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *mut f64,
            arg7: *const blas_int,
        ),
    >,
    pub dspr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *mut f64,
        ),
    >,
    pub dspr2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *mut f64,
        ),
    >,
    pub dsyr2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const f64,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *mut f64,
            arg9: *const blas_int,
        ),
    >,
    pub cgemv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub cgbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *const blas_int,
            arg11: *const c_void,
            arg12: *mut c_void,
            arg13: *const blas_int,
        ),
    >,
    pub chemv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *mut c_void,
            arg10: *const blas_int,
        ),
    >,
    pub chbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub chpmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub ctrmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *mut c_void,
            arg8: *const blas_int,
        ),
    >,
    pub ctbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub ctpmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *mut c_void,
            arg7: *const blas_int,
        ),
    >,
    pub ctrsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *mut c_void,
            arg8: *const blas_int,
        ),
    >,
    pub ctbsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub ctpsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *mut c_void,
            arg7: *const blas_int,
        ),
    >,
    pub cgerc_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub cgeru_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub cher_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
            arg7: *const blas_int,
        ),
    >,
    pub cher2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub chpr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f32,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
        ),
    >,
    pub chpr2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
        ),
    >,
    pub zgemv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub zgbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *const blas_int,
            arg11: *const c_void,
            arg12: *mut c_void,
            arg13: *const blas_int,
        ),
    >,
    pub zhemv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *mut c_void,
            arg10: *const blas_int,
        ),
    >,
    pub zhbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const blas_int,
            arg4: *const c_void,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub zhpmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub ztrmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *mut c_void,
            arg8: *const blas_int,
        ),
    >,
    pub ztbmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub ztpmv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *mut c_void,
            arg7: *const blas_int,
        ),
    >,
    pub ztrsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const blas_int,
            arg7: *mut c_void,
            arg8: *const blas_int,
        ),
    >,
    pub ztbsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub ztpsv_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *mut c_void,
            arg7: *const blas_int,
        ),
    >,
    pub zgerc_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub zgeru_: Option<
        unsafe extern "C" fn(
            arg1: *const blas_int,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub zher_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
            arg7: *const blas_int,
        ),
    >,
    pub zher2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
            arg9: *const blas_int,
        ),
    >,
    pub zhpr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const f64,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *mut c_void,
        ),
    >,
    pub zhpr2_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *const blas_int,
            arg3: *const c_void,
            arg4: *const c_void,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *mut c_void,
        ),
    >,
    pub sgemm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const f32,
            arg8: *const blas_int,
            arg9: *const f32,
            arg10: *const blas_int,
            arg11: *const f32,
            arg12: *mut f32,
            arg13: *const blas_int,
        ),
    >,
    pub sgemmtr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f32,
            arg7: *const f32,
            arg8: *const blas_int,
            arg9: *const f32,
            arg10: *const blas_int,
            arg11: *const f32,
            arg12: *mut f32,
            arg13: *const blas_int,
        ),
    >,
    pub ssymm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *const f32,
            arg9: *const blas_int,
            arg10: *const f32,
            arg11: *mut f32,
            arg12: *const blas_int,
        ),
    >,
    pub ssyrk_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *const f32,
            arg9: *mut f32,
            arg10: *const blas_int,
        ),
    >,
    pub ssyr2k_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const f32,
            arg7: *const blas_int,
            arg8: *const f32,
            arg9: *const blas_int,
            arg10: *const f32,
            arg11: *mut f32,
            arg12: *const blas_int,
        ),
    >,
    pub strmm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const f32,
            arg8: *const f32,
            arg9: *const blas_int,
            arg10: *mut f32,
            arg11: *const blas_int,
        ),
    >,
    pub strsm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const f32,
            arg8: *const f32,
            arg9: *const blas_int,
            arg10: *mut f32,
            arg11: *const blas_int,
        ),
    >,
    pub dgemm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const f64,
            arg8: *const blas_int,
            arg9: *const f64,
            arg10: *const blas_int,
            arg11: *const f64,
            arg12: *mut f64,
            arg13: *const blas_int,
        ),
    >,
    pub dgemmtr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const f64,
            arg7: *const f64,
            arg8: *const blas_int,
            arg9: *const f64,
            arg10: *const blas_int,
            arg11: *const f64,
            arg12: *mut f64,
            arg13: *const blas_int,
        ),
    >,
    pub dsymm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *const f64,
            arg9: *const blas_int,
            arg10: *const f64,
            arg11: *mut f64,
            arg12: *const blas_int,
        ),
    >,
    pub dsyrk_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *const f64,
            arg9: *mut f64,
            arg10: *const blas_int,
        ),
    >,
    pub dsyr2k_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const f64,
            arg7: *const blas_int,
            arg8: *const f64,
            arg9: *const blas_int,
            arg10: *const f64,
            arg11: *mut f64,
            arg12: *const blas_int,
        ),
    >,
    pub dtrmm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const f64,
            arg8: *const f64,
            arg9: *const blas_int,
            arg10: *mut f64,
            arg11: *const blas_int,
        ),
    >,
    pub dtrsm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const f64,
            arg8: *const f64,
            arg9: *const blas_int,
            arg10: *mut f64,
            arg11: *const blas_int,
        ),
    >,
    pub cgemm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *const blas_int,
            arg11: *const c_void,
            arg12: *mut c_void,
            arg13: *const blas_int,
        ),
    >,
    pub cgemmtr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *const blas_int,
            arg11: *const c_void,
            arg12: *mut c_void,
            arg13: *const blas_int,
        ),
    >,
    pub csymm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const c_void,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub chemm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const c_void,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub csyrk_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *mut c_void,
            arg10: *const blas_int,
        ),
    >,
    pub cherk_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f32,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const f32,
            arg9: *mut c_void,
            arg10: *const blas_int,
        ),
    >,
    pub csyr2k_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const c_void,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub cher2k_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const f32,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub ctrmm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub ctrsm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub zgemm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *const blas_int,
            arg11: *const c_void,
            arg12: *mut c_void,
            arg13: *const blas_int,
        ),
    >,
    pub zgemmtr_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *const blas_int,
            arg5: *const blas_int,
            arg6: *const c_void,
            arg7: *const c_void,
            arg8: *const blas_int,
            arg9: *const c_void,
            arg10: *const blas_int,
            arg11: *const c_void,
            arg12: *mut c_void,
            arg13: *const blas_int,
        ),
    >,
    pub zsymm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const c_void,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub zhemm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const c_void,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub zsyrk_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *mut c_void,
            arg10: *const blas_int,
        ),
    >,
    pub zherk_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const f64,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const f64,
            arg9: *mut c_void,
            arg10: *const blas_int,
        ),
    >,
    pub zsyr2k_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const c_void,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub zher2k_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *const blas_int,
            arg4: *const blas_int,
            arg5: *const c_void,
            arg6: *const c_void,
            arg7: *const blas_int,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *const f64,
            arg11: *mut c_void,
            arg12: *const blas_int,
        ),
    >,
    pub ztrmm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
    pub ztrsm_: Option<
        unsafe extern "C" fn(
            arg1: *mut c_char,
            arg2: *mut c_char,
            arg3: *mut c_char,
            arg4: *mut c_char,
            arg5: *const blas_int,
            arg6: *const blas_int,
            arg7: *const c_void,
            arg8: *const c_void,
            arg9: *const blas_int,
            arg10: *mut c_void,
            arg11: *const blas_int,
        ),
    >,
}
