//! Library initializer implementation for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;
use libloading::{Library, Symbol};

unsafe fn get_symbol<'f, F>(libs: &'f [Library], name: &[u8]) -> Option<Symbol<'f, F>> {
    libs.iter().find_map(|lib| lib.get::<F>(name).ok())
}

impl DyLoadLib {
    pub unsafe fn new(libs: Vec<libloading::Library>, libs_path: Vec<String>) -> DyLoadLib {
        let mut result = DyLoadLib {
            __libraries: vec![],      // dummy here, set this field later
            __libraries_path: vec![], // dummy here, set this field later
            xerbla_: get_symbol(&libs, b"xerbla_\0").map(|sym| *sym),
            srot_: get_symbol(&libs, b"srot_\0").map(|sym| *sym),
            srotg_: get_symbol(&libs, b"srotg_\0").map(|sym| *sym),
            srotm_: get_symbol(&libs, b"srotm_\0").map(|sym| *sym),
            srotmg_: get_symbol(&libs, b"srotmg_\0").map(|sym| *sym),
            sswap_: get_symbol(&libs, b"sswap_\0").map(|sym| *sym),
            scopy_: get_symbol(&libs, b"scopy_\0").map(|sym| *sym),
            saxpy_: get_symbol(&libs, b"saxpy_\0").map(|sym| *sym),
            sdotsub_: get_symbol(&libs, b"sdotsub_\0").map(|sym| *sym),
            sdsdotsub_: get_symbol(&libs, b"sdsdotsub_\0").map(|sym| *sym),
            sscal_: get_symbol(&libs, b"sscal_\0").map(|sym| *sym),
            snrm2sub_: get_symbol(&libs, b"snrm2sub_\0").map(|sym| *sym),
            sasumsub_: get_symbol(&libs, b"sasumsub_\0").map(|sym| *sym),
            isamaxsub_: get_symbol(&libs, b"isamaxsub_\0").map(|sym| *sym),
            drot_: get_symbol(&libs, b"drot_\0").map(|sym| *sym),
            drotg_: get_symbol(&libs, b"drotg_\0").map(|sym| *sym),
            drotm_: get_symbol(&libs, b"drotm_\0").map(|sym| *sym),
            drotmg_: get_symbol(&libs, b"drotmg_\0").map(|sym| *sym),
            dswap_: get_symbol(&libs, b"dswap_\0").map(|sym| *sym),
            dcopy_: get_symbol(&libs, b"dcopy_\0").map(|sym| *sym),
            daxpy_: get_symbol(&libs, b"daxpy_\0").map(|sym| *sym),
            dsdotsub_: get_symbol(&libs, b"dsdotsub_\0").map(|sym| *sym),
            ddotsub_: get_symbol(&libs, b"ddotsub_\0").map(|sym| *sym),
            dscal_: get_symbol(&libs, b"dscal_\0").map(|sym| *sym),
            dnrm2sub_: get_symbol(&libs, b"dnrm2sub_\0").map(|sym| *sym),
            dasumsub_: get_symbol(&libs, b"dasumsub_\0").map(|sym| *sym),
            idamaxsub_: get_symbol(&libs, b"idamaxsub_\0").map(|sym| *sym),
            crotg_: get_symbol(&libs, b"crotg_\0").map(|sym| *sym),
            csrot_: get_symbol(&libs, b"csrot_\0").map(|sym| *sym),
            cswap_: get_symbol(&libs, b"cswap_\0").map(|sym| *sym),
            ccopy_: get_symbol(&libs, b"ccopy_\0").map(|sym| *sym),
            caxpy_: get_symbol(&libs, b"caxpy_\0").map(|sym| *sym),
            cdotcsub_: get_symbol(&libs, b"cdotcsub_\0").map(|sym| *sym),
            cdotusub_: get_symbol(&libs, b"cdotusub_\0").map(|sym| *sym),
            cscal_: get_symbol(&libs, b"cscal_\0").map(|sym| *sym),
            icamaxsub_: get_symbol(&libs, b"icamaxsub_\0").map(|sym| *sym),
            csscal_: get_symbol(&libs, b"csscal_\0").map(|sym| *sym),
            scnrm2sub_: get_symbol(&libs, b"scnrm2sub_\0").map(|sym| *sym),
            scasumsub_: get_symbol(&libs, b"scasumsub_\0").map(|sym| *sym),
            scabs1sub_: get_symbol(&libs, b"scabs1sub_\0").map(|sym| *sym),
            zrotg_: get_symbol(&libs, b"zrotg_\0").map(|sym| *sym),
            zdrot_: get_symbol(&libs, b"zdrot_\0").map(|sym| *sym),
            zswap_: get_symbol(&libs, b"zswap_\0").map(|sym| *sym),
            zcopy_: get_symbol(&libs, b"zcopy_\0").map(|sym| *sym),
            zaxpy_: get_symbol(&libs, b"zaxpy_\0").map(|sym| *sym),
            zdotcsub_: get_symbol(&libs, b"zdotcsub_\0").map(|sym| *sym),
            zdotusub_: get_symbol(&libs, b"zdotusub_\0").map(|sym| *sym),
            zdscal_: get_symbol(&libs, b"zdscal_\0").map(|sym| *sym),
            zscal_: get_symbol(&libs, b"zscal_\0").map(|sym| *sym),
            dznrm2sub_: get_symbol(&libs, b"dznrm2sub_\0").map(|sym| *sym),
            dzasumsub_: get_symbol(&libs, b"dzasumsub_\0").map(|sym| *sym),
            izamaxsub_: get_symbol(&libs, b"izamaxsub_\0").map(|sym| *sym),
            dcabs1sub_: get_symbol(&libs, b"dcabs1sub_\0").map(|sym| *sym),
            sgemv_: get_symbol(&libs, b"sgemv_\0").map(|sym| *sym),
            sgbmv_: get_symbol(&libs, b"sgbmv_\0").map(|sym| *sym),
            ssymv_: get_symbol(&libs, b"ssymv_\0").map(|sym| *sym),
            ssbmv_: get_symbol(&libs, b"ssbmv_\0").map(|sym| *sym),
            sspmv_: get_symbol(&libs, b"sspmv_\0").map(|sym| *sym),
            strmv_: get_symbol(&libs, b"strmv_\0").map(|sym| *sym),
            stbmv_: get_symbol(&libs, b"stbmv_\0").map(|sym| *sym),
            strsv_: get_symbol(&libs, b"strsv_\0").map(|sym| *sym),
            stbsv_: get_symbol(&libs, b"stbsv_\0").map(|sym| *sym),
            stpmv_: get_symbol(&libs, b"stpmv_\0").map(|sym| *sym),
            stpsv_: get_symbol(&libs, b"stpsv_\0").map(|sym| *sym),
            sger_: get_symbol(&libs, b"sger_\0").map(|sym| *sym),
            ssyr_: get_symbol(&libs, b"ssyr_\0").map(|sym| *sym),
            sspr_: get_symbol(&libs, b"sspr_\0").map(|sym| *sym),
            sspr2_: get_symbol(&libs, b"sspr2_\0").map(|sym| *sym),
            ssyr2_: get_symbol(&libs, b"ssyr2_\0").map(|sym| *sym),
            dgemv_: get_symbol(&libs, b"dgemv_\0").map(|sym| *sym),
            dgbmv_: get_symbol(&libs, b"dgbmv_\0").map(|sym| *sym),
            dsymv_: get_symbol(&libs, b"dsymv_\0").map(|sym| *sym),
            dsbmv_: get_symbol(&libs, b"dsbmv_\0").map(|sym| *sym),
            dspmv_: get_symbol(&libs, b"dspmv_\0").map(|sym| *sym),
            dtrmv_: get_symbol(&libs, b"dtrmv_\0").map(|sym| *sym),
            dtbmv_: get_symbol(&libs, b"dtbmv_\0").map(|sym| *sym),
            dtrsv_: get_symbol(&libs, b"dtrsv_\0").map(|sym| *sym),
            dtbsv_: get_symbol(&libs, b"dtbsv_\0").map(|sym| *sym),
            dtpmv_: get_symbol(&libs, b"dtpmv_\0").map(|sym| *sym),
            dtpsv_: get_symbol(&libs, b"dtpsv_\0").map(|sym| *sym),
            dger_: get_symbol(&libs, b"dger_\0").map(|sym| *sym),
            dsyr_: get_symbol(&libs, b"dsyr_\0").map(|sym| *sym),
            dspr_: get_symbol(&libs, b"dspr_\0").map(|sym| *sym),
            dspr2_: get_symbol(&libs, b"dspr2_\0").map(|sym| *sym),
            dsyr2_: get_symbol(&libs, b"dsyr2_\0").map(|sym| *sym),
            cgemv_: get_symbol(&libs, b"cgemv_\0").map(|sym| *sym),
            cgbmv_: get_symbol(&libs, b"cgbmv_\0").map(|sym| *sym),
            chemv_: get_symbol(&libs, b"chemv_\0").map(|sym| *sym),
            chbmv_: get_symbol(&libs, b"chbmv_\0").map(|sym| *sym),
            chpmv_: get_symbol(&libs, b"chpmv_\0").map(|sym| *sym),
            ctrmv_: get_symbol(&libs, b"ctrmv_\0").map(|sym| *sym),
            ctbmv_: get_symbol(&libs, b"ctbmv_\0").map(|sym| *sym),
            ctpmv_: get_symbol(&libs, b"ctpmv_\0").map(|sym| *sym),
            ctrsv_: get_symbol(&libs, b"ctrsv_\0").map(|sym| *sym),
            ctbsv_: get_symbol(&libs, b"ctbsv_\0").map(|sym| *sym),
            ctpsv_: get_symbol(&libs, b"ctpsv_\0").map(|sym| *sym),
            cgerc_: get_symbol(&libs, b"cgerc_\0").map(|sym| *sym),
            cgeru_: get_symbol(&libs, b"cgeru_\0").map(|sym| *sym),
            cher_: get_symbol(&libs, b"cher_\0").map(|sym| *sym),
            cher2_: get_symbol(&libs, b"cher2_\0").map(|sym| *sym),
            chpr_: get_symbol(&libs, b"chpr_\0").map(|sym| *sym),
            chpr2_: get_symbol(&libs, b"chpr2_\0").map(|sym| *sym),
            zgemv_: get_symbol(&libs, b"zgemv_\0").map(|sym| *sym),
            zgbmv_: get_symbol(&libs, b"zgbmv_\0").map(|sym| *sym),
            zhemv_: get_symbol(&libs, b"zhemv_\0").map(|sym| *sym),
            zhbmv_: get_symbol(&libs, b"zhbmv_\0").map(|sym| *sym),
            zhpmv_: get_symbol(&libs, b"zhpmv_\0").map(|sym| *sym),
            ztrmv_: get_symbol(&libs, b"ztrmv_\0").map(|sym| *sym),
            ztbmv_: get_symbol(&libs, b"ztbmv_\0").map(|sym| *sym),
            ztpmv_: get_symbol(&libs, b"ztpmv_\0").map(|sym| *sym),
            ztrsv_: get_symbol(&libs, b"ztrsv_\0").map(|sym| *sym),
            ztbsv_: get_symbol(&libs, b"ztbsv_\0").map(|sym| *sym),
            ztpsv_: get_symbol(&libs, b"ztpsv_\0").map(|sym| *sym),
            zgerc_: get_symbol(&libs, b"zgerc_\0").map(|sym| *sym),
            zgeru_: get_symbol(&libs, b"zgeru_\0").map(|sym| *sym),
            zher_: get_symbol(&libs, b"zher_\0").map(|sym| *sym),
            zher2_: get_symbol(&libs, b"zher2_\0").map(|sym| *sym),
            zhpr_: get_symbol(&libs, b"zhpr_\0").map(|sym| *sym),
            zhpr2_: get_symbol(&libs, b"zhpr2_\0").map(|sym| *sym),
            sgemm_: get_symbol(&libs, b"sgemm_\0").map(|sym| *sym),
            sgemmtr_: get_symbol(&libs, b"sgemmtr_\0").map(|sym| *sym),
            ssymm_: get_symbol(&libs, b"ssymm_\0").map(|sym| *sym),
            ssyrk_: get_symbol(&libs, b"ssyrk_\0").map(|sym| *sym),
            ssyr2k_: get_symbol(&libs, b"ssyr2k_\0").map(|sym| *sym),
            strmm_: get_symbol(&libs, b"strmm_\0").map(|sym| *sym),
            strsm_: get_symbol(&libs, b"strsm_\0").map(|sym| *sym),
            dgemm_: get_symbol(&libs, b"dgemm_\0").map(|sym| *sym),
            dgemmtr_: get_symbol(&libs, b"dgemmtr_\0").map(|sym| *sym),
            dsymm_: get_symbol(&libs, b"dsymm_\0").map(|sym| *sym),
            dsyrk_: get_symbol(&libs, b"dsyrk_\0").map(|sym| *sym),
            dsyr2k_: get_symbol(&libs, b"dsyr2k_\0").map(|sym| *sym),
            dtrmm_: get_symbol(&libs, b"dtrmm_\0").map(|sym| *sym),
            dtrsm_: get_symbol(&libs, b"dtrsm_\0").map(|sym| *sym),
            cgemm_: get_symbol(&libs, b"cgemm_\0").map(|sym| *sym),
            cgemmtr_: get_symbol(&libs, b"cgemmtr_\0").map(|sym| *sym),
            csymm_: get_symbol(&libs, b"csymm_\0").map(|sym| *sym),
            chemm_: get_symbol(&libs, b"chemm_\0").map(|sym| *sym),
            csyrk_: get_symbol(&libs, b"csyrk_\0").map(|sym| *sym),
            cherk_: get_symbol(&libs, b"cherk_\0").map(|sym| *sym),
            csyr2k_: get_symbol(&libs, b"csyr2k_\0").map(|sym| *sym),
            cher2k_: get_symbol(&libs, b"cher2k_\0").map(|sym| *sym),
            ctrmm_: get_symbol(&libs, b"ctrmm_\0").map(|sym| *sym),
            ctrsm_: get_symbol(&libs, b"ctrsm_\0").map(|sym| *sym),
            zgemm_: get_symbol(&libs, b"zgemm_\0").map(|sym| *sym),
            zgemmtr_: get_symbol(&libs, b"zgemmtr_\0").map(|sym| *sym),
            zsymm_: get_symbol(&libs, b"zsymm_\0").map(|sym| *sym),
            zhemm_: get_symbol(&libs, b"zhemm_\0").map(|sym| *sym),
            zsyrk_: get_symbol(&libs, b"zsyrk_\0").map(|sym| *sym),
            zherk_: get_symbol(&libs, b"zherk_\0").map(|sym| *sym),
            zsyr2k_: get_symbol(&libs, b"zsyr2k_\0").map(|sym| *sym),
            zher2k_: get_symbol(&libs, b"zher2k_\0").map(|sym| *sym),
            ztrmm_: get_symbol(&libs, b"ztrmm_\0").map(|sym| *sym),
            ztrsm_: get_symbol(&libs, b"ztrsm_\0").map(|sym| *sym),
        };
        result.__libraries = libs;
        result.__libraries_path = libs_path;
        result
    }
}
