//! Base of current FFI.
//!
//! Declaration of types, enums, cargo feature controls, etc.
//!
//! This file is generated automatically.

#![allow(non_camel_case_types)]
pub(crate) use core::ffi::{c_char, c_void};

#[cfg(not(feature = "ilp64"))]
pub type blas_int = i32;
#[cfg(feature = "ilp64")]
pub type blas_int = i64;

/* automatically generated by rust-bindgen 0.71.1 */
