//! Library initializer implementation for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;
use libloading::{Library, Symbol};

unsafe fn get_symbol<'f, F>(libs: &'f [Library], name: &[u8]) -> Option<Symbol<'f, F>> {
    libs.iter().find_map(|lib| lib.get::<F>(name).ok())
}

impl DyLoadLib {
    pub unsafe fn new(libs: Vec<libloading::Library>, libs_path: Vec<String>) -> DyLoadLib {
        let mut result = DyLoadLib {
            __libraries: vec![],      // dummy here, set this field later
            __libraries_path: vec![], // dummy here, set this field later
            cblas_dcabs1: get_symbol(&libs, b"cblas_dcabs1\0").map(|sym| *sym),
            cblas_scabs1: get_symbol(&libs, b"cblas_scabs1\0").map(|sym| *sym),
            cblas_sdsdot: get_symbol(&libs, b"cblas_sdsdot\0").map(|sym| *sym),
            cblas_dsdot: get_symbol(&libs, b"cblas_dsdot\0").map(|sym| *sym),
            cblas_sdot: get_symbol(&libs, b"cblas_sdot\0").map(|sym| *sym),
            cblas_ddot: get_symbol(&libs, b"cblas_ddot\0").map(|sym| *sym),
            cblas_cdotu_sub: get_symbol(&libs, b"cblas_cdotu_sub\0").map(|sym| *sym),
            cblas_cdotc_sub: get_symbol(&libs, b"cblas_cdotc_sub\0").map(|sym| *sym),
            cblas_zdotu_sub: get_symbol(&libs, b"cblas_zdotu_sub\0").map(|sym| *sym),
            cblas_zdotc_sub: get_symbol(&libs, b"cblas_zdotc_sub\0").map(|sym| *sym),
            cblas_snrm2: get_symbol(&libs, b"cblas_snrm2\0").map(|sym| *sym),
            cblas_sasum: get_symbol(&libs, b"cblas_sasum\0").map(|sym| *sym),
            cblas_dnrm2: get_symbol(&libs, b"cblas_dnrm2\0").map(|sym| *sym),
            cblas_dasum: get_symbol(&libs, b"cblas_dasum\0").map(|sym| *sym),
            cblas_scnrm2: get_symbol(&libs, b"cblas_scnrm2\0").map(|sym| *sym),
            cblas_scasum: get_symbol(&libs, b"cblas_scasum\0").map(|sym| *sym),
            cblas_dznrm2: get_symbol(&libs, b"cblas_dznrm2\0").map(|sym| *sym),
            cblas_dzasum: get_symbol(&libs, b"cblas_dzasum\0").map(|sym| *sym),
            cblas_isamax: get_symbol(&libs, b"cblas_isamax\0").map(|sym| *sym),
            cblas_idamax: get_symbol(&libs, b"cblas_idamax\0").map(|sym| *sym),
            cblas_icamax: get_symbol(&libs, b"cblas_icamax\0").map(|sym| *sym),
            cblas_izamax: get_symbol(&libs, b"cblas_izamax\0").map(|sym| *sym),
            cblas_sswap: get_symbol(&libs, b"cblas_sswap\0").map(|sym| *sym),
            cblas_scopy: get_symbol(&libs, b"cblas_scopy\0").map(|sym| *sym),
            cblas_saxpy: get_symbol(&libs, b"cblas_saxpy\0").map(|sym| *sym),
            cblas_dswap: get_symbol(&libs, b"cblas_dswap\0").map(|sym| *sym),
            cblas_dcopy: get_symbol(&libs, b"cblas_dcopy\0").map(|sym| *sym),
            cblas_daxpy: get_symbol(&libs, b"cblas_daxpy\0").map(|sym| *sym),
            cblas_cswap: get_symbol(&libs, b"cblas_cswap\0").map(|sym| *sym),
            cblas_ccopy: get_symbol(&libs, b"cblas_ccopy\0").map(|sym| *sym),
            cblas_caxpy: get_symbol(&libs, b"cblas_caxpy\0").map(|sym| *sym),
            cblas_zswap: get_symbol(&libs, b"cblas_zswap\0").map(|sym| *sym),
            cblas_zcopy: get_symbol(&libs, b"cblas_zcopy\0").map(|sym| *sym),
            cblas_zaxpy: get_symbol(&libs, b"cblas_zaxpy\0").map(|sym| *sym),
            cblas_srotmg: get_symbol(&libs, b"cblas_srotmg\0").map(|sym| *sym),
            cblas_srotm: get_symbol(&libs, b"cblas_srotm\0").map(|sym| *sym),
            cblas_drotmg: get_symbol(&libs, b"cblas_drotmg\0").map(|sym| *sym),
            cblas_drotm: get_symbol(&libs, b"cblas_drotm\0").map(|sym| *sym),
            cblas_sscal: get_symbol(&libs, b"cblas_sscal\0").map(|sym| *sym),
            cblas_dscal: get_symbol(&libs, b"cblas_dscal\0").map(|sym| *sym),
            cblas_cscal: get_symbol(&libs, b"cblas_cscal\0").map(|sym| *sym),
            cblas_zscal: get_symbol(&libs, b"cblas_zscal\0").map(|sym| *sym),
            cblas_csscal: get_symbol(&libs, b"cblas_csscal\0").map(|sym| *sym),
            cblas_zdscal: get_symbol(&libs, b"cblas_zdscal\0").map(|sym| *sym),
            cblas_srotg: get_symbol(&libs, b"cblas_srotg\0").map(|sym| *sym),
            cblas_drotg: get_symbol(&libs, b"cblas_drotg\0").map(|sym| *sym),
            cblas_crotg: get_symbol(&libs, b"cblas_crotg\0").map(|sym| *sym),
            cblas_zrotg: get_symbol(&libs, b"cblas_zrotg\0").map(|sym| *sym),
            cblas_srot: get_symbol(&libs, b"cblas_srot\0").map(|sym| *sym),
            cblas_drot: get_symbol(&libs, b"cblas_drot\0").map(|sym| *sym),
            cblas_csrot: get_symbol(&libs, b"cblas_csrot\0").map(|sym| *sym),
            cblas_zdrot: get_symbol(&libs, b"cblas_zdrot\0").map(|sym| *sym),
            cblas_sgemv: get_symbol(&libs, b"cblas_sgemv\0").map(|sym| *sym),
            cblas_sgbmv: get_symbol(&libs, b"cblas_sgbmv\0").map(|sym| *sym),
            cblas_strmv: get_symbol(&libs, b"cblas_strmv\0").map(|sym| *sym),
            cblas_stbmv: get_symbol(&libs, b"cblas_stbmv\0").map(|sym| *sym),
            cblas_stpmv: get_symbol(&libs, b"cblas_stpmv\0").map(|sym| *sym),
            cblas_strsv: get_symbol(&libs, b"cblas_strsv\0").map(|sym| *sym),
            cblas_stbsv: get_symbol(&libs, b"cblas_stbsv\0").map(|sym| *sym),
            cblas_stpsv: get_symbol(&libs, b"cblas_stpsv\0").map(|sym| *sym),
            cblas_dgemv: get_symbol(&libs, b"cblas_dgemv\0").map(|sym| *sym),
            cblas_dgbmv: get_symbol(&libs, b"cblas_dgbmv\0").map(|sym| *sym),
            cblas_dtrmv: get_symbol(&libs, b"cblas_dtrmv\0").map(|sym| *sym),
            cblas_dtbmv: get_symbol(&libs, b"cblas_dtbmv\0").map(|sym| *sym),
            cblas_dtpmv: get_symbol(&libs, b"cblas_dtpmv\0").map(|sym| *sym),
            cblas_dtrsv: get_symbol(&libs, b"cblas_dtrsv\0").map(|sym| *sym),
            cblas_dtbsv: get_symbol(&libs, b"cblas_dtbsv\0").map(|sym| *sym),
            cblas_dtpsv: get_symbol(&libs, b"cblas_dtpsv\0").map(|sym| *sym),
            cblas_cgemv: get_symbol(&libs, b"cblas_cgemv\0").map(|sym| *sym),
            cblas_cgbmv: get_symbol(&libs, b"cblas_cgbmv\0").map(|sym| *sym),
            cblas_ctrmv: get_symbol(&libs, b"cblas_ctrmv\0").map(|sym| *sym),
            cblas_ctbmv: get_symbol(&libs, b"cblas_ctbmv\0").map(|sym| *sym),
            cblas_ctpmv: get_symbol(&libs, b"cblas_ctpmv\0").map(|sym| *sym),
            cblas_ctrsv: get_symbol(&libs, b"cblas_ctrsv\0").map(|sym| *sym),
            cblas_ctbsv: get_symbol(&libs, b"cblas_ctbsv\0").map(|sym| *sym),
            cblas_ctpsv: get_symbol(&libs, b"cblas_ctpsv\0").map(|sym| *sym),
            cblas_zgemv: get_symbol(&libs, b"cblas_zgemv\0").map(|sym| *sym),
            cblas_zgbmv: get_symbol(&libs, b"cblas_zgbmv\0").map(|sym| *sym),
            cblas_ztrmv: get_symbol(&libs, b"cblas_ztrmv\0").map(|sym| *sym),
            cblas_ztbmv: get_symbol(&libs, b"cblas_ztbmv\0").map(|sym| *sym),
            cblas_ztpmv: get_symbol(&libs, b"cblas_ztpmv\0").map(|sym| *sym),
            cblas_ztrsv: get_symbol(&libs, b"cblas_ztrsv\0").map(|sym| *sym),
            cblas_ztbsv: get_symbol(&libs, b"cblas_ztbsv\0").map(|sym| *sym),
            cblas_ztpsv: get_symbol(&libs, b"cblas_ztpsv\0").map(|sym| *sym),
            cblas_ssymv: get_symbol(&libs, b"cblas_ssymv\0").map(|sym| *sym),
            cblas_ssbmv: get_symbol(&libs, b"cblas_ssbmv\0").map(|sym| *sym),
            cblas_sspmv: get_symbol(&libs, b"cblas_sspmv\0").map(|sym| *sym),
            cblas_sger: get_symbol(&libs, b"cblas_sger\0").map(|sym| *sym),
            cblas_ssyr: get_symbol(&libs, b"cblas_ssyr\0").map(|sym| *sym),
            cblas_sspr: get_symbol(&libs, b"cblas_sspr\0").map(|sym| *sym),
            cblas_ssyr2: get_symbol(&libs, b"cblas_ssyr2\0").map(|sym| *sym),
            cblas_sspr2: get_symbol(&libs, b"cblas_sspr2\0").map(|sym| *sym),
            cblas_dsymv: get_symbol(&libs, b"cblas_dsymv\0").map(|sym| *sym),
            cblas_dsbmv: get_symbol(&libs, b"cblas_dsbmv\0").map(|sym| *sym),
            cblas_dspmv: get_symbol(&libs, b"cblas_dspmv\0").map(|sym| *sym),
            cblas_dger: get_symbol(&libs, b"cblas_dger\0").map(|sym| *sym),
            cblas_dsyr: get_symbol(&libs, b"cblas_dsyr\0").map(|sym| *sym),
            cblas_dspr: get_symbol(&libs, b"cblas_dspr\0").map(|sym| *sym),
            cblas_dsyr2: get_symbol(&libs, b"cblas_dsyr2\0").map(|sym| *sym),
            cblas_dspr2: get_symbol(&libs, b"cblas_dspr2\0").map(|sym| *sym),
            cblas_chemv: get_symbol(&libs, b"cblas_chemv\0").map(|sym| *sym),
            cblas_chbmv: get_symbol(&libs, b"cblas_chbmv\0").map(|sym| *sym),
            cblas_chpmv: get_symbol(&libs, b"cblas_chpmv\0").map(|sym| *sym),
            cblas_cgeru: get_symbol(&libs, b"cblas_cgeru\0").map(|sym| *sym),
            cblas_cgerc: get_symbol(&libs, b"cblas_cgerc\0").map(|sym| *sym),
            cblas_cher: get_symbol(&libs, b"cblas_cher\0").map(|sym| *sym),
            cblas_chpr: get_symbol(&libs, b"cblas_chpr\0").map(|sym| *sym),
            cblas_cher2: get_symbol(&libs, b"cblas_cher2\0").map(|sym| *sym),
            cblas_chpr2: get_symbol(&libs, b"cblas_chpr2\0").map(|sym| *sym),
            cblas_zhemv: get_symbol(&libs, b"cblas_zhemv\0").map(|sym| *sym),
            cblas_zhbmv: get_symbol(&libs, b"cblas_zhbmv\0").map(|sym| *sym),
            cblas_zhpmv: get_symbol(&libs, b"cblas_zhpmv\0").map(|sym| *sym),
            cblas_zgeru: get_symbol(&libs, b"cblas_zgeru\0").map(|sym| *sym),
            cblas_zgerc: get_symbol(&libs, b"cblas_zgerc\0").map(|sym| *sym),
            cblas_zher: get_symbol(&libs, b"cblas_zher\0").map(|sym| *sym),
            cblas_zhpr: get_symbol(&libs, b"cblas_zhpr\0").map(|sym| *sym),
            cblas_zher2: get_symbol(&libs, b"cblas_zher2\0").map(|sym| *sym),
            cblas_zhpr2: get_symbol(&libs, b"cblas_zhpr2\0").map(|sym| *sym),
            cblas_sgemm: get_symbol(&libs, b"cblas_sgemm\0").map(|sym| *sym),
            cblas_sgemmtr: get_symbol(&libs, b"cblas_sgemmtr\0").map(|sym| *sym),
            cblas_ssymm: get_symbol(&libs, b"cblas_ssymm\0").map(|sym| *sym),
            cblas_ssyrk: get_symbol(&libs, b"cblas_ssyrk\0").map(|sym| *sym),
            cblas_ssyr2k: get_symbol(&libs, b"cblas_ssyr2k\0").map(|sym| *sym),
            cblas_strmm: get_symbol(&libs, b"cblas_strmm\0").map(|sym| *sym),
            cblas_strsm: get_symbol(&libs, b"cblas_strsm\0").map(|sym| *sym),
            cblas_dgemm: get_symbol(&libs, b"cblas_dgemm\0").map(|sym| *sym),
            cblas_dgemmtr: get_symbol(&libs, b"cblas_dgemmtr\0").map(|sym| *sym),
            cblas_dsymm: get_symbol(&libs, b"cblas_dsymm\0").map(|sym| *sym),
            cblas_dsyrk: get_symbol(&libs, b"cblas_dsyrk\0").map(|sym| *sym),
            cblas_dsyr2k: get_symbol(&libs, b"cblas_dsyr2k\0").map(|sym| *sym),
            cblas_dtrmm: get_symbol(&libs, b"cblas_dtrmm\0").map(|sym| *sym),
            cblas_dtrsm: get_symbol(&libs, b"cblas_dtrsm\0").map(|sym| *sym),
            cblas_cgemm: get_symbol(&libs, b"cblas_cgemm\0").map(|sym| *sym),
            cblas_cgemmtr: get_symbol(&libs, b"cblas_cgemmtr\0").map(|sym| *sym),
            cblas_csymm: get_symbol(&libs, b"cblas_csymm\0").map(|sym| *sym),
            cblas_csyrk: get_symbol(&libs, b"cblas_csyrk\0").map(|sym| *sym),
            cblas_csyr2k: get_symbol(&libs, b"cblas_csyr2k\0").map(|sym| *sym),
            cblas_ctrmm: get_symbol(&libs, b"cblas_ctrmm\0").map(|sym| *sym),
            cblas_ctrsm: get_symbol(&libs, b"cblas_ctrsm\0").map(|sym| *sym),
            cblas_zgemm: get_symbol(&libs, b"cblas_zgemm\0").map(|sym| *sym),
            cblas_zgemmtr: get_symbol(&libs, b"cblas_zgemmtr\0").map(|sym| *sym),
            cblas_zsymm: get_symbol(&libs, b"cblas_zsymm\0").map(|sym| *sym),
            cblas_zsyrk: get_symbol(&libs, b"cblas_zsyrk\0").map(|sym| *sym),
            cblas_zsyr2k: get_symbol(&libs, b"cblas_zsyr2k\0").map(|sym| *sym),
            cblas_ztrmm: get_symbol(&libs, b"cblas_ztrmm\0").map(|sym| *sym),
            cblas_ztrsm: get_symbol(&libs, b"cblas_ztrsm\0").map(|sym| *sym),
            cblas_chemm: get_symbol(&libs, b"cblas_chemm\0").map(|sym| *sym),
            cblas_cherk: get_symbol(&libs, b"cblas_cherk\0").map(|sym| *sym),
            cblas_cher2k: get_symbol(&libs, b"cblas_cher2k\0").map(|sym| *sym),
            cblas_zhemm: get_symbol(&libs, b"cblas_zhemm\0").map(|sym| *sym),
            cblas_zherk: get_symbol(&libs, b"cblas_zherk\0").map(|sym| *sym),
            cblas_zher2k: get_symbol(&libs, b"cblas_zher2k\0").map(|sym| *sym),
            cblas_xerbla: get_symbol(&libs, b"cblas_xerbla\0").map(|sym| *sym),
        };
        result.__libraries = libs;
        result.__libraries_path = libs_path;
        result
    }
}
