//! Base of current FFI.
//!
//! Declaration of types, enums, cargo feature controls, etc.
//!
//! This file is generated automatically.

pub(crate) use core::ffi::*;
pub use rstsr_cblas_base::*;

/* automatically generated by rust-bindgen 0.71.1 */
