//! Library initializer implementation for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;
use libloading::{Library, Symbol};

unsafe fn get_symbol<'f, F>(libs: &'f [Library], name: &[u8]) -> Option<Symbol<'f, F>> {
    libs.iter().find_map(|lib| lib.get::<F>(name).ok())
}

impl DyLoadLib {
    pub unsafe fn new(libs: Vec<libloading::Library>, libs_path: Vec<String>) -> DyLoadLib {
        let mut result = DyLoadLib {
            __libraries: vec![],      // dummy here, set this field later
            __libraries_path: vec![], // dummy here, set this field later
            xerbla: get_symbol(&libs, b"xerbla\0").map(|sym| *sym),
            lsame: get_symbol(&libs, b"lsame\0").map(|sym| *sym),
            scabs1: get_symbol(&libs, b"scabs1\0").map(|sym| *sym),
            sasum: get_symbol(&libs, b"sasum\0").map(|sym| *sym),
            saxpy: get_symbol(&libs, b"saxpy\0").map(|sym| *sym),
            saxpby: get_symbol(&libs, b"saxpby\0").map(|sym| *sym),
            saxpyi: get_symbol(&libs, b"saxpyi\0").map(|sym| *sym),
            scasum: get_symbol(&libs, b"scasum\0").map(|sym| *sym),
            scnrm2: get_symbol(&libs, b"scnrm2\0").map(|sym| *sym),
            scopy: get_symbol(&libs, b"scopy\0").map(|sym| *sym),
            sdot: get_symbol(&libs, b"sdot\0").map(|sym| *sym),
            sdoti: get_symbol(&libs, b"sdoti\0").map(|sym| *sym),
            sdsdot: get_symbol(&libs, b"sdsdot\0").map(|sym| *sym),
            sgthr: get_symbol(&libs, b"sgthr\0").map(|sym| *sym),
            sgthrz: get_symbol(&libs, b"sgthrz\0").map(|sym| *sym),
            snrm2: get_symbol(&libs, b"snrm2\0").map(|sym| *sym),
            srot: get_symbol(&libs, b"srot\0").map(|sym| *sym),
            srotg: get_symbol(&libs, b"srotg\0").map(|sym| *sym),
            sroti: get_symbol(&libs, b"sroti\0").map(|sym| *sym),
            srotm: get_symbol(&libs, b"srotm\0").map(|sym| *sym),
            srotmg: get_symbol(&libs, b"srotmg\0").map(|sym| *sym),
            sscal: get_symbol(&libs, b"sscal\0").map(|sym| *sym),
            ssctr: get_symbol(&libs, b"ssctr\0").map(|sym| *sym),
            sswap: get_symbol(&libs, b"sswap\0").map(|sym| *sym),
            isamax: get_symbol(&libs, b"isamax\0").map(|sym| *sym),
            isamin: get_symbol(&libs, b"isamin\0").map(|sym| *sym),
            caxpy: get_symbol(&libs, b"caxpy\0").map(|sym| *sym),
            caxpby: get_symbol(&libs, b"caxpby\0").map(|sym| *sym),
            caxpyi: get_symbol(&libs, b"caxpyi\0").map(|sym| *sym),
            ccopy: get_symbol(&libs, b"ccopy\0").map(|sym| *sym),
            cdotc: get_symbol(&libs, b"cdotc\0").map(|sym| *sym),
            cdotci: get_symbol(&libs, b"cdotci\0").map(|sym| *sym),
            cdotu: get_symbol(&libs, b"cdotu\0").map(|sym| *sym),
            cdotui: get_symbol(&libs, b"cdotui\0").map(|sym| *sym),
            cgthr: get_symbol(&libs, b"cgthr\0").map(|sym| *sym),
            cgthrz: get_symbol(&libs, b"cgthrz\0").map(|sym| *sym),
            crot: get_symbol(&libs, b"crot\0").map(|sym| *sym),
            crotg: get_symbol(&libs, b"crotg\0").map(|sym| *sym),
            cscal: get_symbol(&libs, b"cscal\0").map(|sym| *sym),
            csctr: get_symbol(&libs, b"csctr\0").map(|sym| *sym),
            csrot: get_symbol(&libs, b"csrot\0").map(|sym| *sym),
            csscal: get_symbol(&libs, b"csscal\0").map(|sym| *sym),
            cswap: get_symbol(&libs, b"cswap\0").map(|sym| *sym),
            icamax: get_symbol(&libs, b"icamax\0").map(|sym| *sym),
            icamin: get_symbol(&libs, b"icamin\0").map(|sym| *sym),
            dcabs1: get_symbol(&libs, b"dcabs1\0").map(|sym| *sym),
            dasum: get_symbol(&libs, b"dasum\0").map(|sym| *sym),
            daxpy: get_symbol(&libs, b"daxpy\0").map(|sym| *sym),
            daxpby: get_symbol(&libs, b"daxpby\0").map(|sym| *sym),
            daxpyi: get_symbol(&libs, b"daxpyi\0").map(|sym| *sym),
            dcopy: get_symbol(&libs, b"dcopy\0").map(|sym| *sym),
            ddot: get_symbol(&libs, b"ddot\0").map(|sym| *sym),
            dsdot: get_symbol(&libs, b"dsdot\0").map(|sym| *sym),
            ddoti: get_symbol(&libs, b"ddoti\0").map(|sym| *sym),
            dgthr: get_symbol(&libs, b"dgthr\0").map(|sym| *sym),
            dgthrz: get_symbol(&libs, b"dgthrz\0").map(|sym| *sym),
            dnrm2: get_symbol(&libs, b"dnrm2\0").map(|sym| *sym),
            drot: get_symbol(&libs, b"drot\0").map(|sym| *sym),
            drotg: get_symbol(&libs, b"drotg\0").map(|sym| *sym),
            droti: get_symbol(&libs, b"droti\0").map(|sym| *sym),
            drotm: get_symbol(&libs, b"drotm\0").map(|sym| *sym),
            drotmg: get_symbol(&libs, b"drotmg\0").map(|sym| *sym),
            dscal: get_symbol(&libs, b"dscal\0").map(|sym| *sym),
            dsctr: get_symbol(&libs, b"dsctr\0").map(|sym| *sym),
            dswap: get_symbol(&libs, b"dswap\0").map(|sym| *sym),
            dzasum: get_symbol(&libs, b"dzasum\0").map(|sym| *sym),
            dznrm2: get_symbol(&libs, b"dznrm2\0").map(|sym| *sym),
            idamax: get_symbol(&libs, b"idamax\0").map(|sym| *sym),
            idamin: get_symbol(&libs, b"idamin\0").map(|sym| *sym),
            zaxpy: get_symbol(&libs, b"zaxpy\0").map(|sym| *sym),
            zaxpby: get_symbol(&libs, b"zaxpby\0").map(|sym| *sym),
            zaxpyi: get_symbol(&libs, b"zaxpyi\0").map(|sym| *sym),
            zcopy: get_symbol(&libs, b"zcopy\0").map(|sym| *sym),
            zdotc: get_symbol(&libs, b"zdotc\0").map(|sym| *sym),
            zdotci: get_symbol(&libs, b"zdotci\0").map(|sym| *sym),
            zdotu: get_symbol(&libs, b"zdotu\0").map(|sym| *sym),
            zdotui: get_symbol(&libs, b"zdotui\0").map(|sym| *sym),
            zdrot: get_symbol(&libs, b"zdrot\0").map(|sym| *sym),
            zdscal: get_symbol(&libs, b"zdscal\0").map(|sym| *sym),
            zgthr: get_symbol(&libs, b"zgthr\0").map(|sym| *sym),
            zgthrz: get_symbol(&libs, b"zgthrz\0").map(|sym| *sym),
            zrot: get_symbol(&libs, b"zrot\0").map(|sym| *sym),
            zrotg: get_symbol(&libs, b"zrotg\0").map(|sym| *sym),
            zscal: get_symbol(&libs, b"zscal\0").map(|sym| *sym),
            zsctr: get_symbol(&libs, b"zsctr\0").map(|sym| *sym),
            zswap: get_symbol(&libs, b"zswap\0").map(|sym| *sym),
            izamax: get_symbol(&libs, b"izamax\0").map(|sym| *sym),
            izamin: get_symbol(&libs, b"izamin\0").map(|sym| *sym),
            sgbmv: get_symbol(&libs, b"sgbmv\0").map(|sym| *sym),
            sgemv: get_symbol(&libs, b"sgemv\0").map(|sym| *sym),
            sger: get_symbol(&libs, b"sger\0").map(|sym| *sym),
            ssbmv: get_symbol(&libs, b"ssbmv\0").map(|sym| *sym),
            sspmv: get_symbol(&libs, b"sspmv\0").map(|sym| *sym),
            sspr: get_symbol(&libs, b"sspr\0").map(|sym| *sym),
            sspr2: get_symbol(&libs, b"sspr2\0").map(|sym| *sym),
            ssymv: get_symbol(&libs, b"ssymv\0").map(|sym| *sym),
            ssyr: get_symbol(&libs, b"ssyr\0").map(|sym| *sym),
            ssyr2: get_symbol(&libs, b"ssyr2\0").map(|sym| *sym),
            stbmv: get_symbol(&libs, b"stbmv\0").map(|sym| *sym),
            stbsv: get_symbol(&libs, b"stbsv\0").map(|sym| *sym),
            stpmv: get_symbol(&libs, b"stpmv\0").map(|sym| *sym),
            stpsv: get_symbol(&libs, b"stpsv\0").map(|sym| *sym),
            strmv: get_symbol(&libs, b"strmv\0").map(|sym| *sym),
            strsv: get_symbol(&libs, b"strsv\0").map(|sym| *sym),
            sgem2vu: get_symbol(&libs, b"sgem2vu\0").map(|sym| *sym),
            cgbmv: get_symbol(&libs, b"cgbmv\0").map(|sym| *sym),
            cgemv: get_symbol(&libs, b"cgemv\0").map(|sym| *sym),
            cgerc: get_symbol(&libs, b"cgerc\0").map(|sym| *sym),
            cgeru: get_symbol(&libs, b"cgeru\0").map(|sym| *sym),
            chbmv: get_symbol(&libs, b"chbmv\0").map(|sym| *sym),
            chemv: get_symbol(&libs, b"chemv\0").map(|sym| *sym),
            cher: get_symbol(&libs, b"cher\0").map(|sym| *sym),
            cher2: get_symbol(&libs, b"cher2\0").map(|sym| *sym),
            chpmv: get_symbol(&libs, b"chpmv\0").map(|sym| *sym),
            chpr: get_symbol(&libs, b"chpr\0").map(|sym| *sym),
            chpr2: get_symbol(&libs, b"chpr2\0").map(|sym| *sym),
            ctbmv: get_symbol(&libs, b"ctbmv\0").map(|sym| *sym),
            ctbsv: get_symbol(&libs, b"ctbsv\0").map(|sym| *sym),
            ctpmv: get_symbol(&libs, b"ctpmv\0").map(|sym| *sym),
            ctpsv: get_symbol(&libs, b"ctpsv\0").map(|sym| *sym),
            ctrmv: get_symbol(&libs, b"ctrmv\0").map(|sym| *sym),
            ctrsv: get_symbol(&libs, b"ctrsv\0").map(|sym| *sym),
            cgem2vc: get_symbol(&libs, b"cgem2vc\0").map(|sym| *sym),
            scgemv: get_symbol(&libs, b"scgemv\0").map(|sym| *sym),
            dgbmv: get_symbol(&libs, b"dgbmv\0").map(|sym| *sym),
            dgemv: get_symbol(&libs, b"dgemv\0").map(|sym| *sym),
            dger: get_symbol(&libs, b"dger\0").map(|sym| *sym),
            dsbmv: get_symbol(&libs, b"dsbmv\0").map(|sym| *sym),
            dspmv: get_symbol(&libs, b"dspmv\0").map(|sym| *sym),
            dspr: get_symbol(&libs, b"dspr\0").map(|sym| *sym),
            dspr2: get_symbol(&libs, b"dspr2\0").map(|sym| *sym),
            dsymv: get_symbol(&libs, b"dsymv\0").map(|sym| *sym),
            dsyr: get_symbol(&libs, b"dsyr\0").map(|sym| *sym),
            dsyr2: get_symbol(&libs, b"dsyr2\0").map(|sym| *sym),
            dtbmv: get_symbol(&libs, b"dtbmv\0").map(|sym| *sym),
            dtbsv: get_symbol(&libs, b"dtbsv\0").map(|sym| *sym),
            dtpmv: get_symbol(&libs, b"dtpmv\0").map(|sym| *sym),
            dtpsv: get_symbol(&libs, b"dtpsv\0").map(|sym| *sym),
            dtrmv: get_symbol(&libs, b"dtrmv\0").map(|sym| *sym),
            dtrsv: get_symbol(&libs, b"dtrsv\0").map(|sym| *sym),
            dgem2vu: get_symbol(&libs, b"dgem2vu\0").map(|sym| *sym),
            zgbmv: get_symbol(&libs, b"zgbmv\0").map(|sym| *sym),
            zgemv: get_symbol(&libs, b"zgemv\0").map(|sym| *sym),
            zgerc: get_symbol(&libs, b"zgerc\0").map(|sym| *sym),
            zgeru: get_symbol(&libs, b"zgeru\0").map(|sym| *sym),
            zhbmv: get_symbol(&libs, b"zhbmv\0").map(|sym| *sym),
            zhemv: get_symbol(&libs, b"zhemv\0").map(|sym| *sym),
            zher: get_symbol(&libs, b"zher\0").map(|sym| *sym),
            zher2: get_symbol(&libs, b"zher2\0").map(|sym| *sym),
            zhpmv: get_symbol(&libs, b"zhpmv\0").map(|sym| *sym),
            zhpr: get_symbol(&libs, b"zhpr\0").map(|sym| *sym),
            zhpr2: get_symbol(&libs, b"zhpr2\0").map(|sym| *sym),
            ztbmv: get_symbol(&libs, b"ztbmv\0").map(|sym| *sym),
            ztbsv: get_symbol(&libs, b"ztbsv\0").map(|sym| *sym),
            ztpmv: get_symbol(&libs, b"ztpmv\0").map(|sym| *sym),
            ztpsv: get_symbol(&libs, b"ztpsv\0").map(|sym| *sym),
            ztrmv: get_symbol(&libs, b"ztrmv\0").map(|sym| *sym),
            ztrsv: get_symbol(&libs, b"ztrsv\0").map(|sym| *sym),
            zgem2vc: get_symbol(&libs, b"zgem2vc\0").map(|sym| *sym),
            dzgemv: get_symbol(&libs, b"dzgemv\0").map(|sym| *sym),
            sgemm: get_symbol(&libs, b"sgemm\0").map(|sym| *sym),
            sgemm_pack_get_size: get_symbol(&libs, b"sgemm_pack_get_size\0").map(|sym| *sym),
            sgemm_pack: get_symbol(&libs, b"sgemm_pack\0").map(|sym| *sym),
            sgemm_compute: get_symbol(&libs, b"sgemm_compute\0").map(|sym| *sym),
            sgemm_batch: get_symbol(&libs, b"sgemm_batch\0").map(|sym| *sym),
            sgemm_batch_strided: get_symbol(&libs, b"sgemm_batch_strided\0").map(|sym| *sym),
            sgemmt: get_symbol(&libs, b"sgemmt\0").map(|sym| *sym),
            ssymm: get_symbol(&libs, b"ssymm\0").map(|sym| *sym),
            ssyr2k: get_symbol(&libs, b"ssyr2k\0").map(|sym| *sym),
            ssyrk: get_symbol(&libs, b"ssyrk\0").map(|sym| *sym),
            ssyrk_batch: get_symbol(&libs, b"ssyrk_batch\0").map(|sym| *sym),
            ssyrk_batch_strided: get_symbol(&libs, b"ssyrk_batch_strided\0").map(|sym| *sym),
            strmm: get_symbol(&libs, b"strmm\0").map(|sym| *sym),
            strmm_oop: get_symbol(&libs, b"strmm_oop\0").map(|sym| *sym),
            strsm: get_symbol(&libs, b"strsm\0").map(|sym| *sym),
            strsm_oop: get_symbol(&libs, b"strsm_oop\0").map(|sym| *sym),
            strsm_batch: get_symbol(&libs, b"strsm_batch\0").map(|sym| *sym),
            strsm_batch_strided: get_symbol(&libs, b"strsm_batch_strided\0").map(|sym| *sym),
            cgemm: get_symbol(&libs, b"cgemm\0").map(|sym| *sym),
            cgemm_batch: get_symbol(&libs, b"cgemm_batch\0").map(|sym| *sym),
            cgemm_batch_strided: get_symbol(&libs, b"cgemm_batch_strided\0").map(|sym| *sym),
            scgemm: get_symbol(&libs, b"scgemm\0").map(|sym| *sym),
            cgemm3m: get_symbol(&libs, b"cgemm3m\0").map(|sym| *sym),
            cgemm3m_batch: get_symbol(&libs, b"cgemm3m_batch\0").map(|sym| *sym),
            cgemm3m_batch_strided: get_symbol(&libs, b"cgemm3m_batch_strided\0").map(|sym| *sym),
            cgemmt: get_symbol(&libs, b"cgemmt\0").map(|sym| *sym),
            chemm: get_symbol(&libs, b"chemm\0").map(|sym| *sym),
            cher2k: get_symbol(&libs, b"cher2k\0").map(|sym| *sym),
            cherk: get_symbol(&libs, b"cherk\0").map(|sym| *sym),
            csymm: get_symbol(&libs, b"csymm\0").map(|sym| *sym),
            csyr2k: get_symbol(&libs, b"csyr2k\0").map(|sym| *sym),
            csyrk: get_symbol(&libs, b"csyrk\0").map(|sym| *sym),
            csyrk_batch: get_symbol(&libs, b"csyrk_batch\0").map(|sym| *sym),
            csyrk_batch_strided: get_symbol(&libs, b"csyrk_batch_strided\0").map(|sym| *sym),
            ctrmm: get_symbol(&libs, b"ctrmm\0").map(|sym| *sym),
            ctrmm_oop: get_symbol(&libs, b"ctrmm_oop\0").map(|sym| *sym),
            ctrsm: get_symbol(&libs, b"ctrsm\0").map(|sym| *sym),
            ctrsm_oop: get_symbol(&libs, b"ctrsm_oop\0").map(|sym| *sym),
            ctrsm_batch: get_symbol(&libs, b"ctrsm_batch\0").map(|sym| *sym),
            ctrsm_batch_strided: get_symbol(&libs, b"ctrsm_batch_strided\0").map(|sym| *sym),
            dgemm: get_symbol(&libs, b"dgemm\0").map(|sym| *sym),
            dgemm_pack_get_size: get_symbol(&libs, b"dgemm_pack_get_size\0").map(|sym| *sym),
            dgemm_pack: get_symbol(&libs, b"dgemm_pack\0").map(|sym| *sym),
            dgemm_compute: get_symbol(&libs, b"dgemm_compute\0").map(|sym| *sym),
            dgemm_batch: get_symbol(&libs, b"dgemm_batch\0").map(|sym| *sym),
            dgemm_batch_strided: get_symbol(&libs, b"dgemm_batch_strided\0").map(|sym| *sym),
            dgemmt: get_symbol(&libs, b"dgemmt\0").map(|sym| *sym),
            dsymm: get_symbol(&libs, b"dsymm\0").map(|sym| *sym),
            dsyr2k: get_symbol(&libs, b"dsyr2k\0").map(|sym| *sym),
            dsyrk: get_symbol(&libs, b"dsyrk\0").map(|sym| *sym),
            dsyrk_batch: get_symbol(&libs, b"dsyrk_batch\0").map(|sym| *sym),
            dsyrk_batch_strided: get_symbol(&libs, b"dsyrk_batch_strided\0").map(|sym| *sym),
            dtrmm: get_symbol(&libs, b"dtrmm\0").map(|sym| *sym),
            dtrmm_oop: get_symbol(&libs, b"dtrmm_oop\0").map(|sym| *sym),
            dtrsm: get_symbol(&libs, b"dtrsm\0").map(|sym| *sym),
            dtrsm_oop: get_symbol(&libs, b"dtrsm_oop\0").map(|sym| *sym),
            dtrsm_batch: get_symbol(&libs, b"dtrsm_batch\0").map(|sym| *sym),
            dtrsm_batch_strided: get_symbol(&libs, b"dtrsm_batch_strided\0").map(|sym| *sym),
            zgemm: get_symbol(&libs, b"zgemm\0").map(|sym| *sym),
            zgemm_batch: get_symbol(&libs, b"zgemm_batch\0").map(|sym| *sym),
            zgemm_batch_strided: get_symbol(&libs, b"zgemm_batch_strided\0").map(|sym| *sym),
            dzgemm: get_symbol(&libs, b"dzgemm\0").map(|sym| *sym),
            zgemm3m: get_symbol(&libs, b"zgemm3m\0").map(|sym| *sym),
            zgemm3m_batch: get_symbol(&libs, b"zgemm3m_batch\0").map(|sym| *sym),
            zgemm3m_batch_strided: get_symbol(&libs, b"zgemm3m_batch_strided\0").map(|sym| *sym),
            zgemmt: get_symbol(&libs, b"zgemmt\0").map(|sym| *sym),
            zhemm: get_symbol(&libs, b"zhemm\0").map(|sym| *sym),
            zher2k: get_symbol(&libs, b"zher2k\0").map(|sym| *sym),
            zherk: get_symbol(&libs, b"zherk\0").map(|sym| *sym),
            zsymm: get_symbol(&libs, b"zsymm\0").map(|sym| *sym),
            zsyr2k: get_symbol(&libs, b"zsyr2k\0").map(|sym| *sym),
            zsyrk: get_symbol(&libs, b"zsyrk\0").map(|sym| *sym),
            zsyrk_batch: get_symbol(&libs, b"zsyrk_batch\0").map(|sym| *sym),
            zsyrk_batch_strided: get_symbol(&libs, b"zsyrk_batch_strided\0").map(|sym| *sym),
            ztrmm: get_symbol(&libs, b"ztrmm\0").map(|sym| *sym),
            ztrmm_oop: get_symbol(&libs, b"ztrmm_oop\0").map(|sym| *sym),
            ztrsm: get_symbol(&libs, b"ztrsm\0").map(|sym| *sym),
            ztrsm_oop: get_symbol(&libs, b"ztrsm_oop\0").map(|sym| *sym),
            ztrsm_batch: get_symbol(&libs, b"ztrsm_batch\0").map(|sym| *sym),
            ztrsm_batch_strided: get_symbol(&libs, b"ztrsm_batch_strided\0").map(|sym| *sym),
            gemm_s16s16s32: get_symbol(&libs, b"gemm_s16s16s32\0").map(|sym| *sym),
            gemm_s8u8s32: get_symbol(&libs, b"gemm_s8u8s32\0").map(|sym| *sym),
            gemm_bf16bf16f32: get_symbol(&libs, b"gemm_bf16bf16f32\0").map(|sym| *sym),
            gemm_f16f16f32: get_symbol(&libs, b"gemm_f16f16f32\0").map(|sym| *sym),
            gemm_e5m2e5m2f32: get_symbol(&libs, b"gemm_e5m2e5m2f32\0").map(|sym| *sym),
            gemm_e4m3e4m3f32: get_symbol(&libs, b"gemm_e4m3e4m3f32\0").map(|sym| *sym),
            gemm_s8u8s32_pack_get_size: get_symbol(&libs, b"gemm_s8u8s32_pack_get_size\0")
                .map(|sym| *sym),
            gemm_s16s16s32_pack_get_size: get_symbol(&libs, b"gemm_s16s16s32_pack_get_size\0")
                .map(|sym| *sym),
            gemm_bf16bf16f32_pack_get_size: get_symbol(&libs, b"gemm_bf16bf16f32_pack_get_size\0")
                .map(|sym| *sym),
            gemm_f16f16f32_pack_get_size: get_symbol(&libs, b"gemm_f16f16f32_pack_get_size\0")
                .map(|sym| *sym),
            gemm_e5m2e5m2f32_pack_get_size: get_symbol(&libs, b"gemm_e5m2e5m2f32_pack_get_size\0")
                .map(|sym| *sym),
            gemm_e4m3e4m3f32_pack_get_size: get_symbol(&libs, b"gemm_e4m3e4m3f32_pack_get_size\0")
                .map(|sym| *sym),
            gemm_s8u8s32_pack: get_symbol(&libs, b"gemm_s8u8s32_pack\0").map(|sym| *sym),
            gemm_s16s16s32_pack: get_symbol(&libs, b"gemm_s16s16s32_pack\0").map(|sym| *sym),
            gemm_bf16bf16f32_pack: get_symbol(&libs, b"gemm_bf16bf16f32_pack\0").map(|sym| *sym),
            gemm_f16f16f32_pack: get_symbol(&libs, b"gemm_f16f16f32_pack\0").map(|sym| *sym),
            gemm_e5m2e5m2f32_pack: get_symbol(&libs, b"gemm_e5m2e5m2f32_pack\0").map(|sym| *sym),
            gemm_e4m3e4m3f32_pack: get_symbol(&libs, b"gemm_e4m3e4m3f32_pack\0").map(|sym| *sym),
            gemm_s8u8s32_compute: get_symbol(&libs, b"gemm_s8u8s32_compute\0").map(|sym| *sym),
            gemm_s16s16s32_compute: get_symbol(&libs, b"gemm_s16s16s32_compute\0").map(|sym| *sym),
            gemm_bf16bf16f32_compute: get_symbol(&libs, b"gemm_bf16bf16f32_compute\0")
                .map(|sym| *sym),
            gemm_f16f16f32_compute: get_symbol(&libs, b"gemm_f16f16f32_compute\0").map(|sym| *sym),
            gemm_e5m2e5m2f32_compute: get_symbol(&libs, b"gemm_e5m2e5m2f32_compute\0")
                .map(|sym| *sym),
            gemm_e4m3e4m3f32_compute: get_symbol(&libs, b"gemm_e4m3e4m3f32_compute\0")
                .map(|sym| *sym),
            hgemm: get_symbol(&libs, b"hgemm\0").map(|sym| *sym),
            hgemm_pack_get_size: get_symbol(&libs, b"hgemm_pack_get_size\0").map(|sym| *sym),
            hgemm_pack: get_symbol(&libs, b"hgemm_pack\0").map(|sym| *sym),
            hgemm_compute: get_symbol(&libs, b"hgemm_compute\0").map(|sym| *sym),
            mkl_cblas_jit_create_dgemm: get_symbol(&libs, b"mkl_cblas_jit_create_dgemm\0")
                .map(|sym| *sym),
            mkl_cblas_jit_create_sgemm: get_symbol(&libs, b"mkl_cblas_jit_create_sgemm\0")
                .map(|sym| *sym),
            mkl_cblas_jit_create_cgemm: get_symbol(&libs, b"mkl_cblas_jit_create_cgemm\0")
                .map(|sym| *sym),
            mkl_cblas_jit_create_zgemm: get_symbol(&libs, b"mkl_cblas_jit_create_zgemm\0")
                .map(|sym| *sym),
            mkl_jit_get_dgemm_ptr: get_symbol(&libs, b"mkl_jit_get_dgemm_ptr\0").map(|sym| *sym),
            mkl_jit_get_sgemm_ptr: get_symbol(&libs, b"mkl_jit_get_sgemm_ptr\0").map(|sym| *sym),
            mkl_jit_get_cgemm_ptr: get_symbol(&libs, b"mkl_jit_get_cgemm_ptr\0").map(|sym| *sym),
            mkl_jit_get_zgemm_ptr: get_symbol(&libs, b"mkl_jit_get_zgemm_ptr\0").map(|sym| *sym),
            mkl_jit_destroy: get_symbol(&libs, b"mkl_jit_destroy\0").map(|sym| *sym),
            saxpy_batch: get_symbol(&libs, b"saxpy_batch\0").map(|sym| *sym),
            daxpy_batch: get_symbol(&libs, b"daxpy_batch\0").map(|sym| *sym),
            caxpy_batch: get_symbol(&libs, b"caxpy_batch\0").map(|sym| *sym),
            zaxpy_batch: get_symbol(&libs, b"zaxpy_batch\0").map(|sym| *sym),
            scopy_batch: get_symbol(&libs, b"scopy_batch\0").map(|sym| *sym),
            dcopy_batch: get_symbol(&libs, b"dcopy_batch\0").map(|sym| *sym),
            ccopy_batch: get_symbol(&libs, b"ccopy_batch\0").map(|sym| *sym),
            zcopy_batch: get_symbol(&libs, b"zcopy_batch\0").map(|sym| *sym),
            saxpy_batch_strided: get_symbol(&libs, b"saxpy_batch_strided\0").map(|sym| *sym),
            daxpy_batch_strided: get_symbol(&libs, b"daxpy_batch_strided\0").map(|sym| *sym),
            caxpy_batch_strided: get_symbol(&libs, b"caxpy_batch_strided\0").map(|sym| *sym),
            zaxpy_batch_strided: get_symbol(&libs, b"zaxpy_batch_strided\0").map(|sym| *sym),
            scopy_batch_strided: get_symbol(&libs, b"scopy_batch_strided\0").map(|sym| *sym),
            dcopy_batch_strided: get_symbol(&libs, b"dcopy_batch_strided\0").map(|sym| *sym),
            ccopy_batch_strided: get_symbol(&libs, b"ccopy_batch_strided\0").map(|sym| *sym),
            zcopy_batch_strided: get_symbol(&libs, b"zcopy_batch_strided\0").map(|sym| *sym),
            sgemv_batch: get_symbol(&libs, b"sgemv_batch\0").map(|sym| *sym),
            sgemv_batch_strided: get_symbol(&libs, b"sgemv_batch_strided\0").map(|sym| *sym),
            dgemv_batch: get_symbol(&libs, b"dgemv_batch\0").map(|sym| *sym),
            dgemv_batch_strided: get_symbol(&libs, b"dgemv_batch_strided\0").map(|sym| *sym),
            cgemv_batch: get_symbol(&libs, b"cgemv_batch\0").map(|sym| *sym),
            cgemv_batch_strided: get_symbol(&libs, b"cgemv_batch_strided\0").map(|sym| *sym),
            zgemv_batch: get_symbol(&libs, b"zgemv_batch\0").map(|sym| *sym),
            zgemv_batch_strided: get_symbol(&libs, b"zgemv_batch_strided\0").map(|sym| *sym),
            sdgmm_batch: get_symbol(&libs, b"sdgmm_batch\0").map(|sym| *sym),
            sdgmm_batch_strided: get_symbol(&libs, b"sdgmm_batch_strided\0").map(|sym| *sym),
            ddgmm_batch: get_symbol(&libs, b"ddgmm_batch\0").map(|sym| *sym),
            ddgmm_batch_strided: get_symbol(&libs, b"ddgmm_batch_strided\0").map(|sym| *sym),
            cdgmm_batch: get_symbol(&libs, b"cdgmm_batch\0").map(|sym| *sym),
            cdgmm_batch_strided: get_symbol(&libs, b"cdgmm_batch_strided\0").map(|sym| *sym),
            zdgmm_batch: get_symbol(&libs, b"zdgmm_batch\0").map(|sym| *sym),
            zdgmm_batch_strided: get_symbol(&libs, b"zdgmm_batch_strided\0").map(|sym| *sym),
        };
        result.__libraries = libs;
        result.__libraries_path = libs_path;
        result
    }
}
