//! Library initializer implementation for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;
use libloading::{Library, Symbol};

unsafe fn get_symbol<'f, F>(libs: &'f [Library], name: &[u8]) -> Option<Symbol<'f, F>> {
    libs.iter().find_map(|lib| lib.get::<F>(name).ok())
}

impl DyLoadLib {
    pub unsafe fn new(libs: Vec<libloading::Library>, libs_path: Vec<String>) -> DyLoadLib {
        let mut result = DyLoadLib {
            __libraries: vec![],      // dummy here, set this field later
            __libraries_path: vec![], // dummy here, set this field later
            xerbla_: get_symbol(&libs, b"xerbla_\0").map(|sym| *sym),
            lsame_: get_symbol(&libs, b"lsame_\0").map(|sym| *sym),
            scabs1_: get_symbol(&libs, b"scabs1_\0").map(|sym| *sym),
            sasum_: get_symbol(&libs, b"sasum_\0").map(|sym| *sym),
            saxpy_: get_symbol(&libs, b"saxpy_\0").map(|sym| *sym),
            saxpby_: get_symbol(&libs, b"saxpby_\0").map(|sym| *sym),
            saxpyi_: get_symbol(&libs, b"saxpyi_\0").map(|sym| *sym),
            scasum_: get_symbol(&libs, b"scasum_\0").map(|sym| *sym),
            scnrm2_: get_symbol(&libs, b"scnrm2_\0").map(|sym| *sym),
            scopy_: get_symbol(&libs, b"scopy_\0").map(|sym| *sym),
            sdot_: get_symbol(&libs, b"sdot_\0").map(|sym| *sym),
            sdoti_: get_symbol(&libs, b"sdoti_\0").map(|sym| *sym),
            sdsdot_: get_symbol(&libs, b"sdsdot_\0").map(|sym| *sym),
            sgthr_: get_symbol(&libs, b"sgthr_\0").map(|sym| *sym),
            sgthrz_: get_symbol(&libs, b"sgthrz_\0").map(|sym| *sym),
            snrm2_: get_symbol(&libs, b"snrm2_\0").map(|sym| *sym),
            srot_: get_symbol(&libs, b"srot_\0").map(|sym| *sym),
            srotg_: get_symbol(&libs, b"srotg_\0").map(|sym| *sym),
            sroti_: get_symbol(&libs, b"sroti_\0").map(|sym| *sym),
            srotm_: get_symbol(&libs, b"srotm_\0").map(|sym| *sym),
            srotmg_: get_symbol(&libs, b"srotmg_\0").map(|sym| *sym),
            sscal_: get_symbol(&libs, b"sscal_\0").map(|sym| *sym),
            ssctr_: get_symbol(&libs, b"ssctr_\0").map(|sym| *sym),
            sswap_: get_symbol(&libs, b"sswap_\0").map(|sym| *sym),
            isamax_: get_symbol(&libs, b"isamax_\0").map(|sym| *sym),
            isamin_: get_symbol(&libs, b"isamin_\0").map(|sym| *sym),
            caxpy_: get_symbol(&libs, b"caxpy_\0").map(|sym| *sym),
            caxpby_: get_symbol(&libs, b"caxpby_\0").map(|sym| *sym),
            caxpyi_: get_symbol(&libs, b"caxpyi_\0").map(|sym| *sym),
            ccopy_: get_symbol(&libs, b"ccopy_\0").map(|sym| *sym),
            cdotc_: get_symbol(&libs, b"cdotc_\0").map(|sym| *sym),
            cdotci_: get_symbol(&libs, b"cdotci_\0").map(|sym| *sym),
            cdotu_: get_symbol(&libs, b"cdotu_\0").map(|sym| *sym),
            cdotui_: get_symbol(&libs, b"cdotui_\0").map(|sym| *sym),
            cgthr_: get_symbol(&libs, b"cgthr_\0").map(|sym| *sym),
            cgthrz_: get_symbol(&libs, b"cgthrz_\0").map(|sym| *sym),
            crot_: get_symbol(&libs, b"crot_\0").map(|sym| *sym),
            crotg_: get_symbol(&libs, b"crotg_\0").map(|sym| *sym),
            cscal_: get_symbol(&libs, b"cscal_\0").map(|sym| *sym),
            csctr_: get_symbol(&libs, b"csctr_\0").map(|sym| *sym),
            csrot_: get_symbol(&libs, b"csrot_\0").map(|sym| *sym),
            csscal_: get_symbol(&libs, b"csscal_\0").map(|sym| *sym),
            cswap_: get_symbol(&libs, b"cswap_\0").map(|sym| *sym),
            icamax_: get_symbol(&libs, b"icamax_\0").map(|sym| *sym),
            icamin_: get_symbol(&libs, b"icamin_\0").map(|sym| *sym),
            dcabs1_: get_symbol(&libs, b"dcabs1_\0").map(|sym| *sym),
            dasum_: get_symbol(&libs, b"dasum_\0").map(|sym| *sym),
            daxpy_: get_symbol(&libs, b"daxpy_\0").map(|sym| *sym),
            daxpby_: get_symbol(&libs, b"daxpby_\0").map(|sym| *sym),
            daxpyi_: get_symbol(&libs, b"daxpyi_\0").map(|sym| *sym),
            dcopy_: get_symbol(&libs, b"dcopy_\0").map(|sym| *sym),
            ddot_: get_symbol(&libs, b"ddot_\0").map(|sym| *sym),
            dsdot_: get_symbol(&libs, b"dsdot_\0").map(|sym| *sym),
            ddoti_: get_symbol(&libs, b"ddoti_\0").map(|sym| *sym),
            dgthr_: get_symbol(&libs, b"dgthr_\0").map(|sym| *sym),
            dgthrz_: get_symbol(&libs, b"dgthrz_\0").map(|sym| *sym),
            dnrm2_: get_symbol(&libs, b"dnrm2_\0").map(|sym| *sym),
            drot_: get_symbol(&libs, b"drot_\0").map(|sym| *sym),
            drotg_: get_symbol(&libs, b"drotg_\0").map(|sym| *sym),
            droti_: get_symbol(&libs, b"droti_\0").map(|sym| *sym),
            drotm_: get_symbol(&libs, b"drotm_\0").map(|sym| *sym),
            drotmg_: get_symbol(&libs, b"drotmg_\0").map(|sym| *sym),
            dscal_: get_symbol(&libs, b"dscal_\0").map(|sym| *sym),
            dsctr_: get_symbol(&libs, b"dsctr_\0").map(|sym| *sym),
            dswap_: get_symbol(&libs, b"dswap_\0").map(|sym| *sym),
            dzasum_: get_symbol(&libs, b"dzasum_\0").map(|sym| *sym),
            dznrm2_: get_symbol(&libs, b"dznrm2_\0").map(|sym| *sym),
            idamax_: get_symbol(&libs, b"idamax_\0").map(|sym| *sym),
            idamin_: get_symbol(&libs, b"idamin_\0").map(|sym| *sym),
            zaxpy_: get_symbol(&libs, b"zaxpy_\0").map(|sym| *sym),
            zaxpby_: get_symbol(&libs, b"zaxpby_\0").map(|sym| *sym),
            zaxpyi_: get_symbol(&libs, b"zaxpyi_\0").map(|sym| *sym),
            zcopy_: get_symbol(&libs, b"zcopy_\0").map(|sym| *sym),
            zdotc_: get_symbol(&libs, b"zdotc_\0").map(|sym| *sym),
            zdotci_: get_symbol(&libs, b"zdotci_\0").map(|sym| *sym),
            zdotu_: get_symbol(&libs, b"zdotu_\0").map(|sym| *sym),
            zdotui_: get_symbol(&libs, b"zdotui_\0").map(|sym| *sym),
            zdrot_: get_symbol(&libs, b"zdrot_\0").map(|sym| *sym),
            zdscal_: get_symbol(&libs, b"zdscal_\0").map(|sym| *sym),
            zgthr_: get_symbol(&libs, b"zgthr_\0").map(|sym| *sym),
            zgthrz_: get_symbol(&libs, b"zgthrz_\0").map(|sym| *sym),
            zrot_: get_symbol(&libs, b"zrot_\0").map(|sym| *sym),
            zrotg_: get_symbol(&libs, b"zrotg_\0").map(|sym| *sym),
            zscal_: get_symbol(&libs, b"zscal_\0").map(|sym| *sym),
            zsctr_: get_symbol(&libs, b"zsctr_\0").map(|sym| *sym),
            zswap_: get_symbol(&libs, b"zswap_\0").map(|sym| *sym),
            izamax_: get_symbol(&libs, b"izamax_\0").map(|sym| *sym),
            izamin_: get_symbol(&libs, b"izamin_\0").map(|sym| *sym),
            sgbmv_: get_symbol(&libs, b"sgbmv_\0").map(|sym| *sym),
            sgemv_: get_symbol(&libs, b"sgemv_\0").map(|sym| *sym),
            sger_: get_symbol(&libs, b"sger_\0").map(|sym| *sym),
            ssbmv_: get_symbol(&libs, b"ssbmv_\0").map(|sym| *sym),
            sspmv_: get_symbol(&libs, b"sspmv_\0").map(|sym| *sym),
            sspr_: get_symbol(&libs, b"sspr_\0").map(|sym| *sym),
            sspr2_: get_symbol(&libs, b"sspr2_\0").map(|sym| *sym),
            ssymv_: get_symbol(&libs, b"ssymv_\0").map(|sym| *sym),
            ssyr_: get_symbol(&libs, b"ssyr_\0").map(|sym| *sym),
            ssyr2_: get_symbol(&libs, b"ssyr2_\0").map(|sym| *sym),
            stbmv_: get_symbol(&libs, b"stbmv_\0").map(|sym| *sym),
            stbsv_: get_symbol(&libs, b"stbsv_\0").map(|sym| *sym),
            stpmv_: get_symbol(&libs, b"stpmv_\0").map(|sym| *sym),
            stpsv_: get_symbol(&libs, b"stpsv_\0").map(|sym| *sym),
            strmv_: get_symbol(&libs, b"strmv_\0").map(|sym| *sym),
            strsv_: get_symbol(&libs, b"strsv_\0").map(|sym| *sym),
            sgem2vu_: get_symbol(&libs, b"sgem2vu_\0").map(|sym| *sym),
            cgbmv_: get_symbol(&libs, b"cgbmv_\0").map(|sym| *sym),
            cgemv_: get_symbol(&libs, b"cgemv_\0").map(|sym| *sym),
            cgerc_: get_symbol(&libs, b"cgerc_\0").map(|sym| *sym),
            cgeru_: get_symbol(&libs, b"cgeru_\0").map(|sym| *sym),
            chbmv_: get_symbol(&libs, b"chbmv_\0").map(|sym| *sym),
            chemv_: get_symbol(&libs, b"chemv_\0").map(|sym| *sym),
            cher_: get_symbol(&libs, b"cher_\0").map(|sym| *sym),
            cher2_: get_symbol(&libs, b"cher2_\0").map(|sym| *sym),
            chpmv_: get_symbol(&libs, b"chpmv_\0").map(|sym| *sym),
            chpr_: get_symbol(&libs, b"chpr_\0").map(|sym| *sym),
            chpr2_: get_symbol(&libs, b"chpr2_\0").map(|sym| *sym),
            ctbmv_: get_symbol(&libs, b"ctbmv_\0").map(|sym| *sym),
            ctbsv_: get_symbol(&libs, b"ctbsv_\0").map(|sym| *sym),
            ctpmv_: get_symbol(&libs, b"ctpmv_\0").map(|sym| *sym),
            ctpsv_: get_symbol(&libs, b"ctpsv_\0").map(|sym| *sym),
            ctrmv_: get_symbol(&libs, b"ctrmv_\0").map(|sym| *sym),
            ctrsv_: get_symbol(&libs, b"ctrsv_\0").map(|sym| *sym),
            cgem2vc_: get_symbol(&libs, b"cgem2vc_\0").map(|sym| *sym),
            scgemv_: get_symbol(&libs, b"scgemv_\0").map(|sym| *sym),
            dgbmv_: get_symbol(&libs, b"dgbmv_\0").map(|sym| *sym),
            dgemv_: get_symbol(&libs, b"dgemv_\0").map(|sym| *sym),
            dger_: get_symbol(&libs, b"dger_\0").map(|sym| *sym),
            dsbmv_: get_symbol(&libs, b"dsbmv_\0").map(|sym| *sym),
            dspmv_: get_symbol(&libs, b"dspmv_\0").map(|sym| *sym),
            dspr_: get_symbol(&libs, b"dspr_\0").map(|sym| *sym),
            dspr2_: get_symbol(&libs, b"dspr2_\0").map(|sym| *sym),
            dsymv_: get_symbol(&libs, b"dsymv_\0").map(|sym| *sym),
            dsyr_: get_symbol(&libs, b"dsyr_\0").map(|sym| *sym),
            dsyr2_: get_symbol(&libs, b"dsyr2_\0").map(|sym| *sym),
            dtbmv_: get_symbol(&libs, b"dtbmv_\0").map(|sym| *sym),
            dtbsv_: get_symbol(&libs, b"dtbsv_\0").map(|sym| *sym),
            dtpmv_: get_symbol(&libs, b"dtpmv_\0").map(|sym| *sym),
            dtpsv_: get_symbol(&libs, b"dtpsv_\0").map(|sym| *sym),
            dtrmv_: get_symbol(&libs, b"dtrmv_\0").map(|sym| *sym),
            dtrsv_: get_symbol(&libs, b"dtrsv_\0").map(|sym| *sym),
            dgem2vu_: get_symbol(&libs, b"dgem2vu_\0").map(|sym| *sym),
            zgbmv_: get_symbol(&libs, b"zgbmv_\0").map(|sym| *sym),
            zgemv_: get_symbol(&libs, b"zgemv_\0").map(|sym| *sym),
            zgerc_: get_symbol(&libs, b"zgerc_\0").map(|sym| *sym),
            zgeru_: get_symbol(&libs, b"zgeru_\0").map(|sym| *sym),
            zhbmv_: get_symbol(&libs, b"zhbmv_\0").map(|sym| *sym),
            zhemv_: get_symbol(&libs, b"zhemv_\0").map(|sym| *sym),
            zher_: get_symbol(&libs, b"zher_\0").map(|sym| *sym),
            zher2_: get_symbol(&libs, b"zher2_\0").map(|sym| *sym),
            zhpmv_: get_symbol(&libs, b"zhpmv_\0").map(|sym| *sym),
            zhpr_: get_symbol(&libs, b"zhpr_\0").map(|sym| *sym),
            zhpr2_: get_symbol(&libs, b"zhpr2_\0").map(|sym| *sym),
            ztbmv_: get_symbol(&libs, b"ztbmv_\0").map(|sym| *sym),
            ztbsv_: get_symbol(&libs, b"ztbsv_\0").map(|sym| *sym),
            ztpmv_: get_symbol(&libs, b"ztpmv_\0").map(|sym| *sym),
            ztpsv_: get_symbol(&libs, b"ztpsv_\0").map(|sym| *sym),
            ztrmv_: get_symbol(&libs, b"ztrmv_\0").map(|sym| *sym),
            ztrsv_: get_symbol(&libs, b"ztrsv_\0").map(|sym| *sym),
            zgem2vc_: get_symbol(&libs, b"zgem2vc_\0").map(|sym| *sym),
            dzgemv_: get_symbol(&libs, b"dzgemv_\0").map(|sym| *sym),
            sgemm_: get_symbol(&libs, b"sgemm_\0").map(|sym| *sym),
            sgemm_pack_get_size_: get_symbol(&libs, b"sgemm_pack_get_size_\0").map(|sym| *sym),
            sgemm_pack_: get_symbol(&libs, b"sgemm_pack_\0").map(|sym| *sym),
            sgemm_compute_: get_symbol(&libs, b"sgemm_compute_\0").map(|sym| *sym),
            sgemm_batch_: get_symbol(&libs, b"sgemm_batch_\0").map(|sym| *sym),
            sgemm_batch_strided_: get_symbol(&libs, b"sgemm_batch_strided_\0").map(|sym| *sym),
            sgemmt_: get_symbol(&libs, b"sgemmt_\0").map(|sym| *sym),
            ssymm_: get_symbol(&libs, b"ssymm_\0").map(|sym| *sym),
            ssyr2k_: get_symbol(&libs, b"ssyr2k_\0").map(|sym| *sym),
            ssyrk_: get_symbol(&libs, b"ssyrk_\0").map(|sym| *sym),
            ssyrk_batch_: get_symbol(&libs, b"ssyrk_batch_\0").map(|sym| *sym),
            ssyrk_batch_strided_: get_symbol(&libs, b"ssyrk_batch_strided_\0").map(|sym| *sym),
            strmm_: get_symbol(&libs, b"strmm_\0").map(|sym| *sym),
            strmm_oop_: get_symbol(&libs, b"strmm_oop_\0").map(|sym| *sym),
            strsm_: get_symbol(&libs, b"strsm_\0").map(|sym| *sym),
            strsm_oop_: get_symbol(&libs, b"strsm_oop_\0").map(|sym| *sym),
            strsm_batch_: get_symbol(&libs, b"strsm_batch_\0").map(|sym| *sym),
            strsm_batch_strided_: get_symbol(&libs, b"strsm_batch_strided_\0").map(|sym| *sym),
            cgemm_: get_symbol(&libs, b"cgemm_\0").map(|sym| *sym),
            cgemm_batch_: get_symbol(&libs, b"cgemm_batch_\0").map(|sym| *sym),
            cgemm_batch_strided_: get_symbol(&libs, b"cgemm_batch_strided_\0").map(|sym| *sym),
            scgemm_: get_symbol(&libs, b"scgemm_\0").map(|sym| *sym),
            cgemm3m_: get_symbol(&libs, b"cgemm3m_\0").map(|sym| *sym),
            cgemm3m_batch_: get_symbol(&libs, b"cgemm3m_batch_\0").map(|sym| *sym),
            cgemm3m_batch_strided_: get_symbol(&libs, b"cgemm3m_batch_strided_\0").map(|sym| *sym),
            cgemmt_: get_symbol(&libs, b"cgemmt_\0").map(|sym| *sym),
            chemm_: get_symbol(&libs, b"chemm_\0").map(|sym| *sym),
            cher2k_: get_symbol(&libs, b"cher2k_\0").map(|sym| *sym),
            cherk_: get_symbol(&libs, b"cherk_\0").map(|sym| *sym),
            csymm_: get_symbol(&libs, b"csymm_\0").map(|sym| *sym),
            csyr2k_: get_symbol(&libs, b"csyr2k_\0").map(|sym| *sym),
            csyrk_: get_symbol(&libs, b"csyrk_\0").map(|sym| *sym),
            csyrk_batch_: get_symbol(&libs, b"csyrk_batch_\0").map(|sym| *sym),
            csyrk_batch_strided_: get_symbol(&libs, b"csyrk_batch_strided_\0").map(|sym| *sym),
            ctrmm_: get_symbol(&libs, b"ctrmm_\0").map(|sym| *sym),
            ctrmm_oop_: get_symbol(&libs, b"ctrmm_oop_\0").map(|sym| *sym),
            ctrsm_: get_symbol(&libs, b"ctrsm_\0").map(|sym| *sym),
            ctrsm_oop_: get_symbol(&libs, b"ctrsm_oop_\0").map(|sym| *sym),
            ctrsm_batch_: get_symbol(&libs, b"ctrsm_batch_\0").map(|sym| *sym),
            ctrsm_batch_strided_: get_symbol(&libs, b"ctrsm_batch_strided_\0").map(|sym| *sym),
            dgemm_: get_symbol(&libs, b"dgemm_\0").map(|sym| *sym),
            dgemm_pack_get_size_: get_symbol(&libs, b"dgemm_pack_get_size_\0").map(|sym| *sym),
            dgemm_pack_: get_symbol(&libs, b"dgemm_pack_\0").map(|sym| *sym),
            dgemm_compute_: get_symbol(&libs, b"dgemm_compute_\0").map(|sym| *sym),
            dgemm_batch_: get_symbol(&libs, b"dgemm_batch_\0").map(|sym| *sym),
            dgemm_batch_strided_: get_symbol(&libs, b"dgemm_batch_strided_\0").map(|sym| *sym),
            dgemmt_: get_symbol(&libs, b"dgemmt_\0").map(|sym| *sym),
            dsymm_: get_symbol(&libs, b"dsymm_\0").map(|sym| *sym),
            dsyr2k_: get_symbol(&libs, b"dsyr2k_\0").map(|sym| *sym),
            dsyrk_: get_symbol(&libs, b"dsyrk_\0").map(|sym| *sym),
            dsyrk_batch_: get_symbol(&libs, b"dsyrk_batch_\0").map(|sym| *sym),
            dsyrk_batch_strided_: get_symbol(&libs, b"dsyrk_batch_strided_\0").map(|sym| *sym),
            dtrmm_: get_symbol(&libs, b"dtrmm_\0").map(|sym| *sym),
            dtrmm_oop_: get_symbol(&libs, b"dtrmm_oop_\0").map(|sym| *sym),
            dtrsm_: get_symbol(&libs, b"dtrsm_\0").map(|sym| *sym),
            dtrsm_oop_: get_symbol(&libs, b"dtrsm_oop_\0").map(|sym| *sym),
            dtrsm_batch_: get_symbol(&libs, b"dtrsm_batch_\0").map(|sym| *sym),
            dtrsm_batch_strided_: get_symbol(&libs, b"dtrsm_batch_strided_\0").map(|sym| *sym),
            zgemm_: get_symbol(&libs, b"zgemm_\0").map(|sym| *sym),
            zgemm_batch_: get_symbol(&libs, b"zgemm_batch_\0").map(|sym| *sym),
            zgemm_batch_strided_: get_symbol(&libs, b"zgemm_batch_strided_\0").map(|sym| *sym),
            dzgemm_: get_symbol(&libs, b"dzgemm_\0").map(|sym| *sym),
            zgemm3m_: get_symbol(&libs, b"zgemm3m_\0").map(|sym| *sym),
            zgemm3m_batch_: get_symbol(&libs, b"zgemm3m_batch_\0").map(|sym| *sym),
            zgemm3m_batch_strided_: get_symbol(&libs, b"zgemm3m_batch_strided_\0").map(|sym| *sym),
            zgemmt_: get_symbol(&libs, b"zgemmt_\0").map(|sym| *sym),
            zhemm_: get_symbol(&libs, b"zhemm_\0").map(|sym| *sym),
            zher2k_: get_symbol(&libs, b"zher2k_\0").map(|sym| *sym),
            zherk_: get_symbol(&libs, b"zherk_\0").map(|sym| *sym),
            zsymm_: get_symbol(&libs, b"zsymm_\0").map(|sym| *sym),
            zsyr2k_: get_symbol(&libs, b"zsyr2k_\0").map(|sym| *sym),
            zsyrk_: get_symbol(&libs, b"zsyrk_\0").map(|sym| *sym),
            zsyrk_batch_: get_symbol(&libs, b"zsyrk_batch_\0").map(|sym| *sym),
            zsyrk_batch_strided_: get_symbol(&libs, b"zsyrk_batch_strided_\0").map(|sym| *sym),
            ztrmm_: get_symbol(&libs, b"ztrmm_\0").map(|sym| *sym),
            ztrmm_oop_: get_symbol(&libs, b"ztrmm_oop_\0").map(|sym| *sym),
            ztrsm_: get_symbol(&libs, b"ztrsm_\0").map(|sym| *sym),
            ztrsm_oop_: get_symbol(&libs, b"ztrsm_oop_\0").map(|sym| *sym),
            ztrsm_batch_: get_symbol(&libs, b"ztrsm_batch_\0").map(|sym| *sym),
            ztrsm_batch_strided_: get_symbol(&libs, b"ztrsm_batch_strided_\0").map(|sym| *sym),
            gemm_s16s16s32_: get_symbol(&libs, b"gemm_s16s16s32_\0").map(|sym| *sym),
            gemm_s8u8s32_: get_symbol(&libs, b"gemm_s8u8s32_\0").map(|sym| *sym),
            gemm_bf16bf16f32_: get_symbol(&libs, b"gemm_bf16bf16f32_\0").map(|sym| *sym),
            gemm_f16f16f32_: get_symbol(&libs, b"gemm_f16f16f32_\0").map(|sym| *sym),
            gemm_e5m2e5m2f32_: get_symbol(&libs, b"gemm_e5m2e5m2f32_\0").map(|sym| *sym),
            gemm_e4m3e4m3f32_: get_symbol(&libs, b"gemm_e4m3e4m3f32_\0").map(|sym| *sym),
            gemm_s8u8s32_pack_get_size_: get_symbol(&libs, b"gemm_s8u8s32_pack_get_size_\0")
                .map(|sym| *sym),
            gemm_s16s16s32_pack_get_size_: get_symbol(&libs, b"gemm_s16s16s32_pack_get_size_\0")
                .map(|sym| *sym),
            gemm_bf16bf16f32_pack_get_size_: get_symbol(
                &libs,
                b"gemm_bf16bf16f32_pack_get_size_\0",
            )
            .map(|sym| *sym),
            gemm_f16f16f32_pack_get_size_: get_symbol(&libs, b"gemm_f16f16f32_pack_get_size_\0")
                .map(|sym| *sym),
            gemm_e5m2e5m2f32_pack_get_size_: get_symbol(
                &libs,
                b"gemm_e5m2e5m2f32_pack_get_size_\0",
            )
            .map(|sym| *sym),
            gemm_e4m3e4m3f32_pack_get_size_: get_symbol(
                &libs,
                b"gemm_e4m3e4m3f32_pack_get_size_\0",
            )
            .map(|sym| *sym),
            gemm_s8u8s32_pack_: get_symbol(&libs, b"gemm_s8u8s32_pack_\0").map(|sym| *sym),
            gemm_s16s16s32_pack_: get_symbol(&libs, b"gemm_s16s16s32_pack_\0").map(|sym| *sym),
            gemm_bf16bf16f32_pack_: get_symbol(&libs, b"gemm_bf16bf16f32_pack_\0").map(|sym| *sym),
            gemm_f16f16f32_pack_: get_symbol(&libs, b"gemm_f16f16f32_pack_\0").map(|sym| *sym),
            gemm_e5m2e5m2f32_pack_: get_symbol(&libs, b"gemm_e5m2e5m2f32_pack_\0").map(|sym| *sym),
            gemm_e4m3e4m3f32_pack_: get_symbol(&libs, b"gemm_e4m3e4m3f32_pack_\0").map(|sym| *sym),
            gemm_s8u8s32_compute_: get_symbol(&libs, b"gemm_s8u8s32_compute_\0").map(|sym| *sym),
            gemm_s16s16s32_compute_: get_symbol(&libs, b"gemm_s16s16s32_compute_\0")
                .map(|sym| *sym),
            gemm_bf16bf16f32_compute_: get_symbol(&libs, b"gemm_bf16bf16f32_compute_\0")
                .map(|sym| *sym),
            gemm_f16f16f32_compute_: get_symbol(&libs, b"gemm_f16f16f32_compute_\0")
                .map(|sym| *sym),
            gemm_e5m2e5m2f32_compute_: get_symbol(&libs, b"gemm_e5m2e5m2f32_compute_\0")
                .map(|sym| *sym),
            gemm_e4m3e4m3f32_compute_: get_symbol(&libs, b"gemm_e4m3e4m3f32_compute_\0")
                .map(|sym| *sym),
            hgemm_: get_symbol(&libs, b"hgemm_\0").map(|sym| *sym),
            hgemm_pack_get_size_: get_symbol(&libs, b"hgemm_pack_get_size_\0").map(|sym| *sym),
            hgemm_pack_: get_symbol(&libs, b"hgemm_pack_\0").map(|sym| *sym),
            hgemm_compute_: get_symbol(&libs, b"hgemm_compute_\0").map(|sym| *sym),
            mkl_cblas_jit_create_dgemm_: get_symbol(&libs, b"mkl_cblas_jit_create_dgemm_\0")
                .map(|sym| *sym),
            mkl_cblas_jit_create_sgemm_: get_symbol(&libs, b"mkl_cblas_jit_create_sgemm_\0")
                .map(|sym| *sym),
            mkl_cblas_jit_create_cgemm_: get_symbol(&libs, b"mkl_cblas_jit_create_cgemm_\0")
                .map(|sym| *sym),
            mkl_cblas_jit_create_zgemm_: get_symbol(&libs, b"mkl_cblas_jit_create_zgemm_\0")
                .map(|sym| *sym),
            mkl_jit_get_dgemm_ptr_: get_symbol(&libs, b"mkl_jit_get_dgemm_ptr_\0").map(|sym| *sym),
            mkl_jit_get_sgemm_ptr_: get_symbol(&libs, b"mkl_jit_get_sgemm_ptr_\0").map(|sym| *sym),
            mkl_jit_get_cgemm_ptr_: get_symbol(&libs, b"mkl_jit_get_cgemm_ptr_\0").map(|sym| *sym),
            mkl_jit_get_zgemm_ptr_: get_symbol(&libs, b"mkl_jit_get_zgemm_ptr_\0").map(|sym| *sym),
            mkl_jit_destroy_: get_symbol(&libs, b"mkl_jit_destroy_\0").map(|sym| *sym),
            saxpy_batch_: get_symbol(&libs, b"saxpy_batch_\0").map(|sym| *sym),
            daxpy_batch_: get_symbol(&libs, b"daxpy_batch_\0").map(|sym| *sym),
            caxpy_batch_: get_symbol(&libs, b"caxpy_batch_\0").map(|sym| *sym),
            zaxpy_batch_: get_symbol(&libs, b"zaxpy_batch_\0").map(|sym| *sym),
            scopy_batch_: get_symbol(&libs, b"scopy_batch_\0").map(|sym| *sym),
            dcopy_batch_: get_symbol(&libs, b"dcopy_batch_\0").map(|sym| *sym),
            ccopy_batch_: get_symbol(&libs, b"ccopy_batch_\0").map(|sym| *sym),
            zcopy_batch_: get_symbol(&libs, b"zcopy_batch_\0").map(|sym| *sym),
            saxpy_batch_strided_: get_symbol(&libs, b"saxpy_batch_strided_\0").map(|sym| *sym),
            daxpy_batch_strided_: get_symbol(&libs, b"daxpy_batch_strided_\0").map(|sym| *sym),
            caxpy_batch_strided_: get_symbol(&libs, b"caxpy_batch_strided_\0").map(|sym| *sym),
            zaxpy_batch_strided_: get_symbol(&libs, b"zaxpy_batch_strided_\0").map(|sym| *sym),
            scopy_batch_strided_: get_symbol(&libs, b"scopy_batch_strided_\0").map(|sym| *sym),
            dcopy_batch_strided_: get_symbol(&libs, b"dcopy_batch_strided_\0").map(|sym| *sym),
            ccopy_batch_strided_: get_symbol(&libs, b"ccopy_batch_strided_\0").map(|sym| *sym),
            zcopy_batch_strided_: get_symbol(&libs, b"zcopy_batch_strided_\0").map(|sym| *sym),
            sgemv_batch_: get_symbol(&libs, b"sgemv_batch_\0").map(|sym| *sym),
            sgemv_batch_strided_: get_symbol(&libs, b"sgemv_batch_strided_\0").map(|sym| *sym),
            dgemv_batch_: get_symbol(&libs, b"dgemv_batch_\0").map(|sym| *sym),
            dgemv_batch_strided_: get_symbol(&libs, b"dgemv_batch_strided_\0").map(|sym| *sym),
            cgemv_batch_: get_symbol(&libs, b"cgemv_batch_\0").map(|sym| *sym),
            cgemv_batch_strided_: get_symbol(&libs, b"cgemv_batch_strided_\0").map(|sym| *sym),
            zgemv_batch_: get_symbol(&libs, b"zgemv_batch_\0").map(|sym| *sym),
            zgemv_batch_strided_: get_symbol(&libs, b"zgemv_batch_strided_\0").map(|sym| *sym),
            sdgmm_batch_: get_symbol(&libs, b"sdgmm_batch_\0").map(|sym| *sym),
            sdgmm_batch_strided_: get_symbol(&libs, b"sdgmm_batch_strided_\0").map(|sym| *sym),
            ddgmm_batch_: get_symbol(&libs, b"ddgmm_batch_\0").map(|sym| *sym),
            ddgmm_batch_strided_: get_symbol(&libs, b"ddgmm_batch_strided_\0").map(|sym| *sym),
            cdgmm_batch_: get_symbol(&libs, b"cdgmm_batch_\0").map(|sym| *sym),
            cdgmm_batch_strided_: get_symbol(&libs, b"cdgmm_batch_strided_\0").map(|sym| *sym),
            zdgmm_batch_: get_symbol(&libs, b"zdgmm_batch_\0").map(|sym| *sym),
            zdgmm_batch_strided_: get_symbol(&libs, b"zdgmm_batch_strided_\0").map(|sym| *sym),
        };
        result.__libraries = libs;
        result.__libraries_path = libs_path;
        result
    }
}
