//! Library initializer implementation for dynamic-loading.
//!
//! This file is generated automatically.

use super::*;
use libloading::{Library, Symbol};

unsafe fn get_symbol<'f, F>(libs: &'f [Library], name: &[u8]) -> Option<Symbol<'f, F>> {
    libs.iter().find_map(|lib| lib.get::<F>(name).ok())
}

impl DyLoadLib {
    pub unsafe fn new(libs: Vec<libloading::Library>, libs_path: Vec<String>) -> DyLoadLib {
        let mut result = DyLoadLib {
            __libraries: vec![],      // dummy here, set this field later
            __libraries_path: vec![], // dummy here, set this field later
            LAPACKE_xerbla: get_symbol(&libs, b"LAPACKE_xerbla\0").map(|sym| *sym),
            LAPACKE_lsame: get_symbol(&libs, b"LAPACKE_lsame\0").map(|sym| *sym),
            LAPACKE_cgb_trans: get_symbol(&libs, b"LAPACKE_cgb_trans\0").map(|sym| *sym),
            LAPACKE_cge_trans: get_symbol(&libs, b"LAPACKE_cge_trans\0").map(|sym| *sym),
            LAPACKE_cgg_trans: get_symbol(&libs, b"LAPACKE_cgg_trans\0").map(|sym| *sym),
            LAPACKE_chb_trans: get_symbol(&libs, b"LAPACKE_chb_trans\0").map(|sym| *sym),
            LAPACKE_che_trans: get_symbol(&libs, b"LAPACKE_che_trans\0").map(|sym| *sym),
            LAPACKE_chp_trans: get_symbol(&libs, b"LAPACKE_chp_trans\0").map(|sym| *sym),
            LAPACKE_chs_trans: get_symbol(&libs, b"LAPACKE_chs_trans\0").map(|sym| *sym),
            LAPACKE_cpb_trans: get_symbol(&libs, b"LAPACKE_cpb_trans\0").map(|sym| *sym),
            LAPACKE_cpf_trans: get_symbol(&libs, b"LAPACKE_cpf_trans\0").map(|sym| *sym),
            LAPACKE_cpo_trans: get_symbol(&libs, b"LAPACKE_cpo_trans\0").map(|sym| *sym),
            LAPACKE_cpp_trans: get_symbol(&libs, b"LAPACKE_cpp_trans\0").map(|sym| *sym),
            LAPACKE_csp_trans: get_symbol(&libs, b"LAPACKE_csp_trans\0").map(|sym| *sym),
            LAPACKE_csy_trans: get_symbol(&libs, b"LAPACKE_csy_trans\0").map(|sym| *sym),
            LAPACKE_ctb_trans: get_symbol(&libs, b"LAPACKE_ctb_trans\0").map(|sym| *sym),
            LAPACKE_ctf_trans: get_symbol(&libs, b"LAPACKE_ctf_trans\0").map(|sym| *sym),
            LAPACKE_ctp_trans: get_symbol(&libs, b"LAPACKE_ctp_trans\0").map(|sym| *sym),
            LAPACKE_ctr_trans: get_symbol(&libs, b"LAPACKE_ctr_trans\0").map(|sym| *sym),
            LAPACKE_ctz_trans: get_symbol(&libs, b"LAPACKE_ctz_trans\0").map(|sym| *sym),
            LAPACKE_dgb_trans: get_symbol(&libs, b"LAPACKE_dgb_trans\0").map(|sym| *sym),
            LAPACKE_dge_trans: get_symbol(&libs, b"LAPACKE_dge_trans\0").map(|sym| *sym),
            LAPACKE_dgg_trans: get_symbol(&libs, b"LAPACKE_dgg_trans\0").map(|sym| *sym),
            LAPACKE_dhs_trans: get_symbol(&libs, b"LAPACKE_dhs_trans\0").map(|sym| *sym),
            LAPACKE_dpb_trans: get_symbol(&libs, b"LAPACKE_dpb_trans\0").map(|sym| *sym),
            LAPACKE_dpf_trans: get_symbol(&libs, b"LAPACKE_dpf_trans\0").map(|sym| *sym),
            LAPACKE_dpo_trans: get_symbol(&libs, b"LAPACKE_dpo_trans\0").map(|sym| *sym),
            LAPACKE_dpp_trans: get_symbol(&libs, b"LAPACKE_dpp_trans\0").map(|sym| *sym),
            LAPACKE_dsb_trans: get_symbol(&libs, b"LAPACKE_dsb_trans\0").map(|sym| *sym),
            LAPACKE_dsp_trans: get_symbol(&libs, b"LAPACKE_dsp_trans\0").map(|sym| *sym),
            LAPACKE_dsy_trans: get_symbol(&libs, b"LAPACKE_dsy_trans\0").map(|sym| *sym),
            LAPACKE_dtb_trans: get_symbol(&libs, b"LAPACKE_dtb_trans\0").map(|sym| *sym),
            LAPACKE_dtf_trans: get_symbol(&libs, b"LAPACKE_dtf_trans\0").map(|sym| *sym),
            LAPACKE_dtp_trans: get_symbol(&libs, b"LAPACKE_dtp_trans\0").map(|sym| *sym),
            LAPACKE_dtr_trans: get_symbol(&libs, b"LAPACKE_dtr_trans\0").map(|sym| *sym),
            LAPACKE_dtz_trans: get_symbol(&libs, b"LAPACKE_dtz_trans\0").map(|sym| *sym),
            LAPACKE_sgb_trans: get_symbol(&libs, b"LAPACKE_sgb_trans\0").map(|sym| *sym),
            LAPACKE_sge_trans: get_symbol(&libs, b"LAPACKE_sge_trans\0").map(|sym| *sym),
            LAPACKE_sgg_trans: get_symbol(&libs, b"LAPACKE_sgg_trans\0").map(|sym| *sym),
            LAPACKE_shs_trans: get_symbol(&libs, b"LAPACKE_shs_trans\0").map(|sym| *sym),
            LAPACKE_spb_trans: get_symbol(&libs, b"LAPACKE_spb_trans\0").map(|sym| *sym),
            LAPACKE_spf_trans: get_symbol(&libs, b"LAPACKE_spf_trans\0").map(|sym| *sym),
            LAPACKE_spo_trans: get_symbol(&libs, b"LAPACKE_spo_trans\0").map(|sym| *sym),
            LAPACKE_spp_trans: get_symbol(&libs, b"LAPACKE_spp_trans\0").map(|sym| *sym),
            LAPACKE_ssb_trans: get_symbol(&libs, b"LAPACKE_ssb_trans\0").map(|sym| *sym),
            LAPACKE_ssp_trans: get_symbol(&libs, b"LAPACKE_ssp_trans\0").map(|sym| *sym),
            LAPACKE_ssy_trans: get_symbol(&libs, b"LAPACKE_ssy_trans\0").map(|sym| *sym),
            LAPACKE_stb_trans: get_symbol(&libs, b"LAPACKE_stb_trans\0").map(|sym| *sym),
            LAPACKE_stf_trans: get_symbol(&libs, b"LAPACKE_stf_trans\0").map(|sym| *sym),
            LAPACKE_stp_trans: get_symbol(&libs, b"LAPACKE_stp_trans\0").map(|sym| *sym),
            LAPACKE_str_trans: get_symbol(&libs, b"LAPACKE_str_trans\0").map(|sym| *sym),
            LAPACKE_stz_trans: get_symbol(&libs, b"LAPACKE_stz_trans\0").map(|sym| *sym),
            LAPACKE_zgb_trans: get_symbol(&libs, b"LAPACKE_zgb_trans\0").map(|sym| *sym),
            LAPACKE_zge_trans: get_symbol(&libs, b"LAPACKE_zge_trans\0").map(|sym| *sym),
            LAPACKE_zgg_trans: get_symbol(&libs, b"LAPACKE_zgg_trans\0").map(|sym| *sym),
            LAPACKE_zhb_trans: get_symbol(&libs, b"LAPACKE_zhb_trans\0").map(|sym| *sym),
            LAPACKE_zhe_trans: get_symbol(&libs, b"LAPACKE_zhe_trans\0").map(|sym| *sym),
            LAPACKE_zhp_trans: get_symbol(&libs, b"LAPACKE_zhp_trans\0").map(|sym| *sym),
            LAPACKE_zhs_trans: get_symbol(&libs, b"LAPACKE_zhs_trans\0").map(|sym| *sym),
            LAPACKE_zpb_trans: get_symbol(&libs, b"LAPACKE_zpb_trans\0").map(|sym| *sym),
            LAPACKE_zpf_trans: get_symbol(&libs, b"LAPACKE_zpf_trans\0").map(|sym| *sym),
            LAPACKE_zpo_trans: get_symbol(&libs, b"LAPACKE_zpo_trans\0").map(|sym| *sym),
            LAPACKE_zpp_trans: get_symbol(&libs, b"LAPACKE_zpp_trans\0").map(|sym| *sym),
            LAPACKE_zsp_trans: get_symbol(&libs, b"LAPACKE_zsp_trans\0").map(|sym| *sym),
            LAPACKE_zsy_trans: get_symbol(&libs, b"LAPACKE_zsy_trans\0").map(|sym| *sym),
            LAPACKE_ztb_trans: get_symbol(&libs, b"LAPACKE_ztb_trans\0").map(|sym| *sym),
            LAPACKE_ztf_trans: get_symbol(&libs, b"LAPACKE_ztf_trans\0").map(|sym| *sym),
            LAPACKE_ztp_trans: get_symbol(&libs, b"LAPACKE_ztp_trans\0").map(|sym| *sym),
            LAPACKE_ztr_trans: get_symbol(&libs, b"LAPACKE_ztr_trans\0").map(|sym| *sym),
            LAPACKE_ztz_trans: get_symbol(&libs, b"LAPACKE_ztz_trans\0").map(|sym| *sym),
            LAPACKE_c_nancheck: get_symbol(&libs, b"LAPACKE_c_nancheck\0").map(|sym| *sym),
            LAPACKE_d_nancheck: get_symbol(&libs, b"LAPACKE_d_nancheck\0").map(|sym| *sym),
            LAPACKE_s_nancheck: get_symbol(&libs, b"LAPACKE_s_nancheck\0").map(|sym| *sym),
            LAPACKE_z_nancheck: get_symbol(&libs, b"LAPACKE_z_nancheck\0").map(|sym| *sym),
            LAPACKE_cgb_nancheck: get_symbol(&libs, b"LAPACKE_cgb_nancheck\0").map(|sym| *sym),
            LAPACKE_cge_nancheck: get_symbol(&libs, b"LAPACKE_cge_nancheck\0").map(|sym| *sym),
            LAPACKE_cgg_nancheck: get_symbol(&libs, b"LAPACKE_cgg_nancheck\0").map(|sym| *sym),
            LAPACKE_cgt_nancheck: get_symbol(&libs, b"LAPACKE_cgt_nancheck\0").map(|sym| *sym),
            LAPACKE_chb_nancheck: get_symbol(&libs, b"LAPACKE_chb_nancheck\0").map(|sym| *sym),
            LAPACKE_che_nancheck: get_symbol(&libs, b"LAPACKE_che_nancheck\0").map(|sym| *sym),
            LAPACKE_chp_nancheck: get_symbol(&libs, b"LAPACKE_chp_nancheck\0").map(|sym| *sym),
            LAPACKE_chs_nancheck: get_symbol(&libs, b"LAPACKE_chs_nancheck\0").map(|sym| *sym),
            LAPACKE_cpb_nancheck: get_symbol(&libs, b"LAPACKE_cpb_nancheck\0").map(|sym| *sym),
            LAPACKE_cpf_nancheck: get_symbol(&libs, b"LAPACKE_cpf_nancheck\0").map(|sym| *sym),
            LAPACKE_cpo_nancheck: get_symbol(&libs, b"LAPACKE_cpo_nancheck\0").map(|sym| *sym),
            LAPACKE_cpp_nancheck: get_symbol(&libs, b"LAPACKE_cpp_nancheck\0").map(|sym| *sym),
            LAPACKE_cpt_nancheck: get_symbol(&libs, b"LAPACKE_cpt_nancheck\0").map(|sym| *sym),
            LAPACKE_csp_nancheck: get_symbol(&libs, b"LAPACKE_csp_nancheck\0").map(|sym| *sym),
            LAPACKE_cst_nancheck: get_symbol(&libs, b"LAPACKE_cst_nancheck\0").map(|sym| *sym),
            LAPACKE_csy_nancheck: get_symbol(&libs, b"LAPACKE_csy_nancheck\0").map(|sym| *sym),
            LAPACKE_ctb_nancheck: get_symbol(&libs, b"LAPACKE_ctb_nancheck\0").map(|sym| *sym),
            LAPACKE_ctf_nancheck: get_symbol(&libs, b"LAPACKE_ctf_nancheck\0").map(|sym| *sym),
            LAPACKE_ctp_nancheck: get_symbol(&libs, b"LAPACKE_ctp_nancheck\0").map(|sym| *sym),
            LAPACKE_ctr_nancheck: get_symbol(&libs, b"LAPACKE_ctr_nancheck\0").map(|sym| *sym),
            LAPACKE_ctz_nancheck: get_symbol(&libs, b"LAPACKE_ctz_nancheck\0").map(|sym| *sym),
            LAPACKE_dgb_nancheck: get_symbol(&libs, b"LAPACKE_dgb_nancheck\0").map(|sym| *sym),
            LAPACKE_dge_nancheck: get_symbol(&libs, b"LAPACKE_dge_nancheck\0").map(|sym| *sym),
            LAPACKE_dgg_nancheck: get_symbol(&libs, b"LAPACKE_dgg_nancheck\0").map(|sym| *sym),
            LAPACKE_dgt_nancheck: get_symbol(&libs, b"LAPACKE_dgt_nancheck\0").map(|sym| *sym),
            LAPACKE_dhs_nancheck: get_symbol(&libs, b"LAPACKE_dhs_nancheck\0").map(|sym| *sym),
            LAPACKE_dpb_nancheck: get_symbol(&libs, b"LAPACKE_dpb_nancheck\0").map(|sym| *sym),
            LAPACKE_dpf_nancheck: get_symbol(&libs, b"LAPACKE_dpf_nancheck\0").map(|sym| *sym),
            LAPACKE_dpo_nancheck: get_symbol(&libs, b"LAPACKE_dpo_nancheck\0").map(|sym| *sym),
            LAPACKE_dpp_nancheck: get_symbol(&libs, b"LAPACKE_dpp_nancheck\0").map(|sym| *sym),
            LAPACKE_dpt_nancheck: get_symbol(&libs, b"LAPACKE_dpt_nancheck\0").map(|sym| *sym),
            LAPACKE_dsb_nancheck: get_symbol(&libs, b"LAPACKE_dsb_nancheck\0").map(|sym| *sym),
            LAPACKE_dsp_nancheck: get_symbol(&libs, b"LAPACKE_dsp_nancheck\0").map(|sym| *sym),
            LAPACKE_dst_nancheck: get_symbol(&libs, b"LAPACKE_dst_nancheck\0").map(|sym| *sym),
            LAPACKE_dsy_nancheck: get_symbol(&libs, b"LAPACKE_dsy_nancheck\0").map(|sym| *sym),
            LAPACKE_dtb_nancheck: get_symbol(&libs, b"LAPACKE_dtb_nancheck\0").map(|sym| *sym),
            LAPACKE_dtf_nancheck: get_symbol(&libs, b"LAPACKE_dtf_nancheck\0").map(|sym| *sym),
            LAPACKE_dtp_nancheck: get_symbol(&libs, b"LAPACKE_dtp_nancheck\0").map(|sym| *sym),
            LAPACKE_dtr_nancheck: get_symbol(&libs, b"LAPACKE_dtr_nancheck\0").map(|sym| *sym),
            LAPACKE_dtz_nancheck: get_symbol(&libs, b"LAPACKE_dtz_nancheck\0").map(|sym| *sym),
            LAPACKE_sgb_nancheck: get_symbol(&libs, b"LAPACKE_sgb_nancheck\0").map(|sym| *sym),
            LAPACKE_sge_nancheck: get_symbol(&libs, b"LAPACKE_sge_nancheck\0").map(|sym| *sym),
            LAPACKE_sgg_nancheck: get_symbol(&libs, b"LAPACKE_sgg_nancheck\0").map(|sym| *sym),
            LAPACKE_sgt_nancheck: get_symbol(&libs, b"LAPACKE_sgt_nancheck\0").map(|sym| *sym),
            LAPACKE_shs_nancheck: get_symbol(&libs, b"LAPACKE_shs_nancheck\0").map(|sym| *sym),
            LAPACKE_spb_nancheck: get_symbol(&libs, b"LAPACKE_spb_nancheck\0").map(|sym| *sym),
            LAPACKE_spf_nancheck: get_symbol(&libs, b"LAPACKE_spf_nancheck\0").map(|sym| *sym),
            LAPACKE_spo_nancheck: get_symbol(&libs, b"LAPACKE_spo_nancheck\0").map(|sym| *sym),
            LAPACKE_spp_nancheck: get_symbol(&libs, b"LAPACKE_spp_nancheck\0").map(|sym| *sym),
            LAPACKE_spt_nancheck: get_symbol(&libs, b"LAPACKE_spt_nancheck\0").map(|sym| *sym),
            LAPACKE_ssb_nancheck: get_symbol(&libs, b"LAPACKE_ssb_nancheck\0").map(|sym| *sym),
            LAPACKE_ssp_nancheck: get_symbol(&libs, b"LAPACKE_ssp_nancheck\0").map(|sym| *sym),
            LAPACKE_sst_nancheck: get_symbol(&libs, b"LAPACKE_sst_nancheck\0").map(|sym| *sym),
            LAPACKE_ssy_nancheck: get_symbol(&libs, b"LAPACKE_ssy_nancheck\0").map(|sym| *sym),
            LAPACKE_stb_nancheck: get_symbol(&libs, b"LAPACKE_stb_nancheck\0").map(|sym| *sym),
            LAPACKE_stf_nancheck: get_symbol(&libs, b"LAPACKE_stf_nancheck\0").map(|sym| *sym),
            LAPACKE_stp_nancheck: get_symbol(&libs, b"LAPACKE_stp_nancheck\0").map(|sym| *sym),
            LAPACKE_str_nancheck: get_symbol(&libs, b"LAPACKE_str_nancheck\0").map(|sym| *sym),
            LAPACKE_stz_nancheck: get_symbol(&libs, b"LAPACKE_stz_nancheck\0").map(|sym| *sym),
            LAPACKE_zgb_nancheck: get_symbol(&libs, b"LAPACKE_zgb_nancheck\0").map(|sym| *sym),
            LAPACKE_zge_nancheck: get_symbol(&libs, b"LAPACKE_zge_nancheck\0").map(|sym| *sym),
            LAPACKE_zgg_nancheck: get_symbol(&libs, b"LAPACKE_zgg_nancheck\0").map(|sym| *sym),
            LAPACKE_zgt_nancheck: get_symbol(&libs, b"LAPACKE_zgt_nancheck\0").map(|sym| *sym),
            LAPACKE_zhb_nancheck: get_symbol(&libs, b"LAPACKE_zhb_nancheck\0").map(|sym| *sym),
            LAPACKE_zhe_nancheck: get_symbol(&libs, b"LAPACKE_zhe_nancheck\0").map(|sym| *sym),
            LAPACKE_zhp_nancheck: get_symbol(&libs, b"LAPACKE_zhp_nancheck\0").map(|sym| *sym),
            LAPACKE_zhs_nancheck: get_symbol(&libs, b"LAPACKE_zhs_nancheck\0").map(|sym| *sym),
            LAPACKE_zpb_nancheck: get_symbol(&libs, b"LAPACKE_zpb_nancheck\0").map(|sym| *sym),
            LAPACKE_zpf_nancheck: get_symbol(&libs, b"LAPACKE_zpf_nancheck\0").map(|sym| *sym),
            LAPACKE_zpo_nancheck: get_symbol(&libs, b"LAPACKE_zpo_nancheck\0").map(|sym| *sym),
            LAPACKE_zpp_nancheck: get_symbol(&libs, b"LAPACKE_zpp_nancheck\0").map(|sym| *sym),
            LAPACKE_zpt_nancheck: get_symbol(&libs, b"LAPACKE_zpt_nancheck\0").map(|sym| *sym),
            LAPACKE_zsp_nancheck: get_symbol(&libs, b"LAPACKE_zsp_nancheck\0").map(|sym| *sym),
            LAPACKE_zst_nancheck: get_symbol(&libs, b"LAPACKE_zst_nancheck\0").map(|sym| *sym),
            LAPACKE_zsy_nancheck: get_symbol(&libs, b"LAPACKE_zsy_nancheck\0").map(|sym| *sym),
            LAPACKE_ztb_nancheck: get_symbol(&libs, b"LAPACKE_ztb_nancheck\0").map(|sym| *sym),
            LAPACKE_ztf_nancheck: get_symbol(&libs, b"LAPACKE_ztf_nancheck\0").map(|sym| *sym),
            LAPACKE_ztp_nancheck: get_symbol(&libs, b"LAPACKE_ztp_nancheck\0").map(|sym| *sym),
            LAPACKE_ztr_nancheck: get_symbol(&libs, b"LAPACKE_ztr_nancheck\0").map(|sym| *sym),
            LAPACKE_ztz_nancheck: get_symbol(&libs, b"LAPACKE_ztz_nancheck\0").map(|sym| *sym),
        };
        result.__libraries = libs;
        result.__libraries_path = libs_path;
        result
    }
}
