[package]
name = "rstsr-lapack-ffi"
version = "0.1.0"
description = "Netlib LAPACK FFI bindings"
readme = "readme.md"

edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]

[features]
ilp64 = []
